### ISSUE TITLE
Add ability to format a list of file paths

### ISSUE THREAD

**Issue by dmcghan** [Trivadis/plsql-formatter-settings#100]
I have a tool that exports DB objects and puts them in a repo and then formats them. Sometimes multiple objects are exported (say dependencies on a parent or multiples of a given object type) and passing a folder to be formatted isn't ideal (mostly because some things that weren't exported would get formatted).

I can go into a loop for each file, but that requires starting SQLcl which isn't the most efficient.

Perhaps adding the ability to pass in a list of file paths or maybe (more practically) a path to say a JSON file with such a list would help. Any thoughts?

**Comment by rafael-trevisan** [comment]
I have a similar case here. I use a pre-commit githook to format the database objects and I loop through the list of DB files that were modified and call the sqlcl for each one of the files in the loop.

**Comment by PhilippSalvisberg** [comment]
@dmcghan I understand that you are processing a set of files based on a script and you'd like to avoid calling SQLcl multiple times, because that's costly (JVM start, class-loading, not a native-image (yet)). 

I see basically the following options to solve to problem:

1. extend the  `format.js` to allow to process a list of chosen files (alternative to `rootPath`)
2. copy the files to be formatted to a temporary directory (tree), call SQLcl and `format.js` once and then copy the formatted files back to the original location

We could  extend `format.js` with a parameter file as you suggested. However, when you need to populate such a parameter file first, you could easily change your process to the second option and copy the files to be formatted to a temporary location and call the formatter for this location. Right?

@rafael-trevisan The second option should be feasible for your case as well.

What do you think?

**Comment by dmcghan** [comment]
> when you need to populate such a parameter file first, you could easily change your process to the second option and copy the files to be formatted to a temporary location and call the formatter for this location. Right?

It's an interesting idea, but it's a lot of copying, first to the temp dir and then back. In some cases, this could be for hundreds of files. Seems like unnecessary work that could be eliminated. Also, if done in `format.js`, it could save others some work as well. I vote for option #1 :)

If you're open to the idea of extending `format.js`, we could spec it out a little here and I could take a look at submitting a PR myself. No promises on timing! ;)

**Comment by PhilippSalvisberg** [comment]
>If you're open to the idea of extending `format.js`, we could spec it out a little here and I could take a look at submitting a PR myself. No promises on timing! ;)

Sounds like a plan. 👍

**Comment by dmcghan** [comment]
Here's the first pass...

1. Update `format.js` to support a new option: --filelist, -f. When enabled, the `<rootPath>` argument would be used to find the file. I'm not married to the name of the option. Any better ideas?
2. Update `format.js` to use `<rootPath>` as a pointer to a file that contains a list of files. I think expecting the file to be a JSON array of file paths (strings) makes the most sense. It should be easy enough for users to write and for `format.js` to parse and iterate over.
3. Update plsql-formatter-settings/sqlcl/README.md to cover the new option.

Any better ideas? Am I missing anything?

**Comment by PhilippSalvisberg** [comment]
I like it. Especially that `format.js` expects either a `<rootPath>` as today or a `<configFile>`. JSON is okay. It should probably end on `.json` to make it distinguishable between <rootPath> and pseudo rootPath `*` (which formats the buffer in SQLcl) and a directory. 

Currently `-r` and `--register` is used as flag without passing values. Other parameters use the style `xyz=value`. So something like `files=value1,value2,value3` would be more consistent with the other existing parameters `ext` and `mext`. The format of the corresponding JSON file can be defined from scratch. Whatever you think is feasible.

My expectation is that the PR comes with new and adapted unit tests. See also https://github.com/Trivadis/plsql-formatter-settings/tree/main/tests/src/test/java/com/trivadis/plsql/formatter/sqlcl/tests ;-) . I'm happy to help here.

**Comment by dmcghan** [comment]
I was thinking the flag would be a new one that doesn't have a value. It would serve as a directive so that `<rootPath>` is treated as a `<configFile>`.

For example, I would run: `script format.js files.json -f`

Then files.json would contain something like this:
```
[
  'relative/path/to/file/1.sql',
  '/full/path/to/file/2.sql'
]
```

Thoughts?

If you agree, perhaps `-f`/`--filelist` should be `-c`/`--configfile` instead?

> The format of the corresponding JSON file can be defined from scratch. Whatever you think is feasible.

If the configfile concept is followed through a little more, perhaps when parsed, the logic could work like:

- If array, treat as list of files
- If object, treat as config file with more options

Then you could have a config file like:
```
{
  arbori: 'path/to/arbori',
  files: [
    'relative/path/to/file/1.sql',
    '/full/path/to/file/2.sql'
  ]
}
```

Just thinking out loud here, maybe there's no real benefit to this...

What do you think?

> My expectation is that the PR comes with new and adapted unit tests.

Ack.

**Comment by PhilippSalvisberg** [comment]
>I was thinking the flag would be a new one that doesn't have a value. It would serve as a directive so that <rootPath> is treated as a <configFile>.
>
>For example, I would run: script format.js files.json -f

I think a flag is not not necessary, because you would never want to format a `.json` file. Here's a possible new usage, which should make it clearer:

```
usage: script format.js {<rootPath>|<config.json>|*} [options]

mandatory arguments:
  <rootPath>      file or path to directory containing files to format (content will be replaced!)
  <config.json>   configuration file in JSON format (must end on .json)
  *               use * to format the SQLcl buffer

options:
  --register, -r  register SQLcl command tvdformat, without processing, no <rootPath> required
  ext=<ext>       comma separated list of file extensions to process, e.g. ext=sql,pks,pkb
  mext=<ext>      comma separated list of markdown file extensions to process, e.g. ext=md,mdown
  xml=<file>      path to the file containing the xml file for advanced format settings
                  xml=default uses default advanced settings included in sqlcl
                  xml=embedded uses advanced settings defined in format.js
  files=<files>   comma separated list of files to process <rootPath> is used for relative paths
  arbori=<file>   path to the file containing the Arbori program for custom format settings
                  arbori=default uses default Arbori program included in sqlcl
```

>Then you could have a config file like:
```
{
  arbori: 'path/to/arbori',
  files: [
    'relative/path/to/file/1.sql',
    '/full/path/to/file/2.sql'
  ]
}
```

Yes. Such a config file make sense IMO. You can define values for the other parameters as well (except maybe `--register`).

**Comment by dmcghan** [comment]
> I think a flag is not not necessary, because you would never want to format a .json file. 

Got it.

> files=<files>   comma separated list of files to process <rootPath> is used for relative paths

For this PR, I think I would skip this bit. I think the `config.json` gives us everything we need for now. What do you think about revisiting this flag in the future if requested?

So the changes would include:
1. Update `format.js` to support passing `<config.json>` instead of `<rootPath>` or `*`. The .json extension will be used to identify the file as a config file. The JSON file could be an array of files to format:
    ```json
    [
      "relative/path/to/file/1.sql",
      "/full/path/to/file/2.sql"
    ]
    ```
    or an object which allows various other parameters and options to be provided:
    ```json
    {
      "arbori": "path/to/arbori",
      "files": [
        "relative/path/to/file/1.sql",
        "/full/path/to/file/2.sql"
      ]
    }
    ```
2. Update `plsql-formatter-settings/sqlcl/README.md` to cover the new feature.
3. Add new and adapted unit tests.

Is that a good summary?

**Comment by PhilippSalvisberg** [comment]
>>files= comma separated list of files to process is used for relative paths

>For this PR, I think I would skip this bit. I think the config.json gives us everything we need for now. What do you think about revisiting this flag in the future if requested?

No problem. I agree. For me a config file is just an alternative way to pass a bunch of parameters. It feels a bit wrong to have more options in the config file. That said, a `files` parameter that requires a `rootPath` doesn't feel right either. So it's fine to leave it out for now.

> Is that a good summary?

Yes, thank you. I'm looking forward to the PR.

**Comment by dmcghan** [comment]
What behavior would you like if an option is specified both as an argument and in the config file? Should one override the other? Maybe display an error?

**Comment by PhilippSalvisberg** [comment]
>What behavior would you like if an option is specified both as an argument and in the config file? Should one override the other? Maybe display an error?

Command line parameters override settings in the config file. Technically the settings in the config file are applied first and the command line parameters afterwards.

**Comment by dmcghan** [comment]
I finished the first pass on the code changes yesterday. I went to look at the tests today and I see you're using Java... Sorry, I don't know Java so I'll have to take you up on your offer for help there! :) 

I still need to update the doc, but I created this PR so you could provide some feedback before I work on that: https://github.com/Trivadis/plsql-formatter-settings/pull/101

**Comment by PhilippSalvisberg** [comment]
Great. I can write the test cases in Java. No problem. Let's discuss the details in the PR.
