### ISSUE TITLE
Error when importing Release SQLDev 20.2.0 trivadis_custom_format.arbori into SQL Developer 20.4.1

### ISSUE THREAD

**Issue by tkleiber** [Trivadis/plsql-formatter-settings#102]
Hi!

I know there is no current version for 20.4.1, but only for remembering of this import error:

![image](https://user-images.githubusercontent.com/2185441/114994623-3e776c00-9e9d-11eb-98b5-fa365c499b53.png)

I use  SQL Developer on Windows 10 Professional.

Kind regards
Torsten

**Comment by PhilippSalvisberg** [comment]
Hi Thorsten, Thanks for reporting this issue. I cannot reproduce it. I tried on macOS. The current version https://github.com/Trivadis/plsql-formatter-settings/blob/main/settings/sql_developer/trivadis_custom_format.arbori should work with 20.4.1. Have you used this version?

**Comment by tkleiber** [comment]
Hi Philip!

No as described in the subject I have used Release SQLDev 20.2.0 from Github, which is the latest for SQLDev. The current version in source code works. So time for a new release?

Best regards
Torsten

**Comment by PhilippSalvisberg** [comment]
Ah I understand. This repo works a bit different. It's described in https://github.com/Trivadis/plsql-formatter-settings#introduction. 

The current setting works for SQLDev 20.4.x and SQLcl 20.4.x. I need to update the README. Unfortunately the SQLDev team decided to release SQLcl quarterly and SQLDev twice a year. Next SQLDev release is expected in June/July 2021.

This repo will focus on the latest formatter libraries. They are provided for SQLcl. SQLcl 21.1 became available yesterday. Therefore I create a release over the weekend and update the README.

**Comment by PhilippSalvisberg** [comment]
Released. See https://github.com/Trivadis/plsql-formatter-settings/releases/tag/sqldev-20.4.1
