### ISSUE TITLE
Question: How does the Import modify existing settings?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [Trivadis/plsql-formatter-settings#108]
Here [https://github.com/Trivadis/plsql-formatter-settings](https://github.com/Trivadis/plsql-formatter-settings) the import of the settings is described. 
What I'm missing (what I should had asked before..) - what happens to the existing settings for "advanced Format" and Arbori? Are they replaced / merged / saved automatically / should  they be saved manualy ??

**Comment by PhilippSalvisberg** [comment]
When you import the settings the existing settings are overwritten (replaced). However, you can restore the factory settings by clicking on the "Reset" button as shown in this screenshot.

![image](https://user-images.githubusercontent.com/3883171/119583696-6eccf700-bdc7-11eb-982a-1b0eb0ba12c5.png)

**Comment by Pierre-de-la-Verre** [comment]
_> When you import the settings the existing settings are overwritten (replaced)._

For Rookies like me it would be helpful to add this information to the instruction, like
a) if you have already personal settings, save them with "Export"
b) import new settings with ...

**Comment by PhilippSalvisberg** [comment]
Well, it's documented with this issue.
