### ISSUE TITLE
Performance of splitArg query

### ISSUE THREAD

**Issue by Vadimtro** [Trivadis/plsql-formatter-settings#109]
When running formatter on big package body it hangs on the splitArg query. Here is the extract from the formatter arbori program run in the debug mode (Program.debug=true) on moderate size input:

```
allArgList:
  [parent) paren_expr_list
;

splittableArgList1:
  [parent) paren_expr_list 
    & [arg1) arg_list 
    & arg1^ = parent
    & [arg2) arg_list 
    & arg2^ = arg1
    & [arg3) arg_list 
    & arg3^ = arg2
    & [arg4) arg_list 
    & arg4^ = arg3
;

splittableArgList2:
    [parent) paren_expr_list 
  --& .isLong('parent')
;

splittableArgList:
    splittableArgList1
  | splittableArgList2 
;

splitArg:
      [node) arg 
    & allArgList.parent < node
    & splittableArgList.parent < node
;
```

```
>=================================<     splitArg
CONJ
  CONJ
    [node) 3026
    allArgList.parent < node
  splittableArgList.parent < node

splitArg dimensions:  node splittableArgList allArgList
**Eval space = 1002x433x433**
dim#2,cardinality=1002
dim#3,cardinality=1002
```

There are 3 independent variables : node that is iterated over the entire parse tree, and allArgList and splittableArgList which are rather big relations. 

Inlining the allArgList.parent like this cuts down one dimension:

```
splitArg:
      [node) arg 
    & allArgListParent < node
    & [allArgListParent) paren_expr_list
    & splittableArgList.parent < node
;

```
```
>=================================<     splitArg
CONJ
  CONJ
    [node) 3026
    CONJ
      allArgListParent < node
      [allArgListParent) 5144
  splittableArgList.parent < node

splitArg dimensions:  node splittableArgList
**Eval space = 1002x433**
dim#2,cardinality=1002
```

This is because for each node the execution scans the list of ancestors to fetch the allArgListParent and this is roughly logarithmic on the size of the input.

**Comment by Vadimtro** [comment]
Here is the format log with the fix of rather significant pl/sql module:

tree depth =349
#tokens =213089
allLeaves eval time = 232       (cardinality=213089)
runOnce eval time = 16       (cardinality=1)
false eval time = 0       (cardinality=0)
"Global definitions" eval time = 0       (cardinality=1)
callback time = 511
eval time = 774
tree depth =349
#tokens =213089
prelude eval time = 0       (cardinality=1)
callback time = 15
brkX2_keep eval time = 0       (cardinality=1)
callback time = 0
brkX2_1 eval time = 185       (cardinality=3145)
brkX2_2 eval time = 78       (cardinality=316)
populateBrkX2EndNodes eval time = 15       (cardinality=3264)
callback time = 339
maxOneEmptyLine eval time = 0       (cardinality=1)
callback time = 16
longArgList eval time = 0       (cardinality=1)
callback time = 16
addLongLines eval time = 52       (cardinality=7588)
callback time = 865
addLongDotted eval time = 38       (cardinality=3526)
callback time = 280
allArgList eval time = 20       (cardinality=3658)
splittableArgList1 eval time = 116       (cardinality=1195)
splittableArgList2 eval time = 116       (cardinality=1485)
splittableArgList eval time = 0       (cardinality=1490)
allExprList eval time = 31       (cardinality=404)
splittableExprList1 eval time = 101       (cardinality=3)
splittableExprList2 eval time = 37       (cardinality=3)
splittableExprList eval time = 0       (cardinality=6)
indentArgListParent eval time = 16       (cardinality=0)
callback time = 0
anonymous JS Block #0 eval time = 0       (cardinality=1)
callback time = 0
**splitArg eval time = 5281       (cardinality=10531)**
callback time = 470
splitExpr eval time = 385       (cardinality=0)
callback time = 0
indentFirstAssocArgs eval time = 15716       (cardinality=0)
callback time = 0
splitLongAssignmentStmt eval time = 69       (cardinality=0)
callback time = 0
splittedNodes eval time = 618       (cardinality=0)
simpleIndentConditions eval time = 7851       (cardinality=15103)
closestAncestorDescendent eval time = 292       (cardinality=0)
mergeStatementNodes eval time = 158       (cardinality=0)
indentedNodes1 eval time = 17       (cardinality=15103)
callback time = 33
indentedNodes2 eval time = 0       (cardinality=15103)
callback time = 24
removeNewlinesBeforeNode eval time = 80       (cardinality=0)
callback time = 0
setSpaceBeforeNode eval time = 83       (cardinality=0)
callback time = 0
_skipWSBeforeNode eval time = 736       (cardinality=52186)
_skipWSBeforeAncNode eval time = 324       (cardinality=8220)
skipWhiteSpaceBeforeNode eval time = 16       (cardinality=60406)
callback time = 16
_skipWSAfterNode eval time = 964       (cardinality=53930)
_skipWSAfterAncNode eval time = 215       (cardinality=4110)
skipWhiteSpaceAfterNode eval time = 16       (cardinality=58040)
callback time = 16
"analytics" eval time = 100       (cardinality=0)
"ids" eval time = 69       (cardinality=48633)
identifiers eval time = 15       (cardinality=48633)
callback time = 34
_extraBrkBefore eval time = 1185       (cardinality=27602)
_extraBrkAfter eval time = 701       (cardinality=12223)
commasInProc eval time = 285       (cardinality=9772)
extraBrkBefore eval time = 8035       (cardinality=27080)
callback time = 22
extraBrkAfter eval time = 3634       (cardinality=12223)
callback time = 4
"decl 1" eval time = 0       (cardinality=1)
callback time = 1
brkX2 eval time = 0       (cardinality=3264)
callback time = 1
rightAlignments eval time = 290       (cardinality=0)
callback time = 0
rightAlignmentsMerge eval time = 68       (cardinality=0)
callback time = 0
_paddedIdsInScope1 eval time = 10590       (cardinality=909)
_paddedIdsInScope2 eval time = 297       (cardinality=0)
_paddedIdsInScopeXmlTableColumn eval time = 49       (cardinality=0)
_paddedIdsInScopeXmlTableColumnDatatype eval time = 50       (cardinality=0)
paddedIdsInScope eval time = 0       (cardinality=909)
callback time = 2
incrementalAlignments eval time = 108       (cardinality=1)
incrementalAlignments callback: null
callback time = 1
pairwiseAlignments00 eval time = 39       (cardinality=0)
pairwiseAlignments0 eval time = 111       (cardinality=0)
pairwiseAlignments1 eval time = 455       (cardinality=35159)
pairwiseAlignments2 eval time = 381       (cardinality=3174)
pairwiseAlignments30 eval time = 46       (cardinality=0)
pairwiseAlignments3 eval time = 131       (cardinality=279)
pairwiseAlignments4 eval time = 129       (cardinality=0)
pairwiseAlignments5 eval time = 42       (cardinality=113)
pairwiseAlignments6 eval time = 65       (cardinality=365)
pairwiseAlignments6_2 eval time = 1020       (cardinality=365)
pairwiseAlignments7 eval time = 1109       (cardinality=1121)
pairwiseAlignments7_3 eval time = 1280       (cardinality=0)
pairwiseAlignments8 eval time = 44       (cardinality=0)
pairwiseAlignments9 eval time = 970       (cardinality=9431)
pairwiseAlignments9_1 eval time = 1160       (cardinality=0)
pairwiseAlignments10 eval time = 37       (cardinality=3447)
pairwiseAlignments11 eval time = 138       (cardinality=13089)
pairwiseAlignments12 eval time = 99       (cardinality=0)
pairwiseAlignmentXmlTable eval time = 163       (cardinality=0)
pairwiseAlignmentXmlTableColumn eval time = 300       (cardinality=0)
pairwiseAlignementAssocArg eval time = 1120       (cardinality=0)
pairwiseAlignementCloseParen eval time = 41       (cardinality=0)
pairwiseAlignmentMergeUpdate eval time = 39       (cardinality=0)
pairwiseAlignments eval time = 102       (cardinality=50007)
callback time = 51
less2Spaces eval time = 297       (cardinality=13199)
callback time = 270
extra5Spaces eval time = 21       (cardinality=0)
callback time = 0
ignoreLineBreaksBeforeNode eval time = 342       (cardinality=17304)
callback time = 4
ignoreLineBreaksAfterNode eval time = 58       (cardinality=13203)
callback time = 3
dontFormatNode eval time = 22       (cardinality=3360)
callback time = 2
timestamp eval time = 0       (cardinality=0)
callback time = 0
indentInExistsXmlTableScalarSubquery eval time = 412       (cardinality=208)
callback time = 69
indentCaseExpression eval time = 31       (cardinality=0)
callback time = 0
indentTokensOnNewLineOfFirstSelectionDirective eval time = 0       (cardinality=1)
callback time = 1701
dontFormatOffOnRanges eval time = 0       (cardinality=1)
callback time = 2083
keepLineBreakAfterSelectHint eval time = 0       (cardinality=1)
callback time = 2027
**eval time = 77673**   (ms)

For comprison, the stock program runs in 50 sec.

**Comment by PhilippSalvisberg** [comment]
Thanks @Vadimtro for this finding and solution to optimize execution time.
I will create a PR with the code changes you suggested.

P.S. The output of `Program.debug = true` and `Program.timing = true` is really valuable.
