### ISSUE TITLE
Wrong format of OPEN ... FOR statement USING

### ISSUE THREAD

**Issue by adrianboangiu** [Trivadis/plsql-formatter-settings#116]
Hello,
Using SQL Developer 21.2 (sqldeveloper-21.2.0.187.1842-x64) and the plsql-formatter-settings from 19.07.2021 I have a problem with the formatting of the statement OPEN ... FOR statement USING.
The settings are:
![image](https://user-images.githubusercontent.com/28983495/126648561-9db23996-b228-4917-a131-1c874c0ea2fc.png)
The code:
DECLARE
   TYPE JobRequestCursor IS REF CURSOR;
   sqlstatement         VARCHAR2(2000);
   cJobRequest          JobRequestCursor;
   ct_planner_closed    INTEGER := 0;
   ct_planner_cancelled INTEGER := 1;
   ct_closed_warranty   INTEGER := 2;
   ct_closed_without_wo INTEGER := 3;
   ct_totally_received  INTEGER := 4;
   ct_false             INTEGER := 0;
BEGIN
   sqlStatement :=
      'SELECT JRJR_CODE '||
      'FROM JOB_REQUEST JobRequest_ '||
      'WHERE JRJR_PRIMARY_REQUEST IS NULL AND '||
      '( JRJR_STATUS IN ( :planner_closed, :planner_cancelled, :closed_warranty, :closed_without_wo ) OR '||
      '( JRJR_STATUS = :totally_received AND '||
      'JRJR_WORK_ORDER IS NULL AND '||
      'JRJR_REPARTITION = :ct_false ) )';
   OPEN cJobRequest FOR sqlStatement
   USING ct_planner_closed, ct_planner_cancelled, ct_closed_warranty, ct_closed_without_wo,  ct_totally_received, ct_false;
END;
/

is wrong formatted in the USING part.
Best regards

**Comment by PhilippSalvisberg** [comment]
With you settings the result looks like this:

```
DECLARE
   TYPE JobRequestCursor IS REF CURSOR;
   sqlstatement         VARCHAR2(2000);
   cJobRequest          JobRequestCursor;
   ct_planner_closed    INTEGER := 0;
   ct_planner_cancelled INTEGER := 1;
   ct_closed_warranty   INTEGER := 2;
   ct_closed_without_wo INTEGER := 3;
   ct_totally_received  INTEGER := 4;
   ct_false             INTEGER := 0;
BEGIN
   sqlStatement :=
      'SELECT JRJR_CODE '
      || 'FROM JOB_REQUEST JobRequest_ '
      || 'WHERE JRJR_PRIMARY_REQUEST IS NULL AND '
      || '( JRJR_STATUS IN ( :planner_closed, :planner_cancelled, :closed_warranty, :closed_without_wo ) OR '
      || '( JRJR_STATUS = :totally_received AND '
      || 'JRJR_WORK_ORDER IS NULL AND '
      || 'JRJR_REPARTITION = :ct_false ) )';
   OPEN cJobRequest FOR sqlStatement
      USING ct_planner_closed, ct_planner_cancelled, ct_closed_warranty, ct_closed_without_wo, ct_totally_received, ct_false;
END;
/
```

What do you expect?

**Comment by adrianboangiu** [comment]
Please see the image below. The values after USING are not alligned as you mention:
![image](https://user-images.githubusercontent.com/28983495/126657224-c6fd01ae-55b6-430d-967a-d71253ce5c77.png)

**Comment by PhilippSalvisberg** [comment]
I formatted the code you provided initially. There should not be any line breaks added in the using clause and other formatting outcome do not match with the current rules at all... 

Have you loaded the configured `dbtools.arbori.home` as described [here](https://github.com/Trivadis/plsql-formatter-settings#configure-dbtoolsarborihome) and loaded `trivadis_custom_format.arbori` in the custom settings?

**Comment by adrianboangiu** [comment]
Yes. I followed the procedure described.
![image](https://user-images.githubusercontent.com/28983495/126659554-64f3a9b3-f999-4c87-b206-c5deedcce9f8.png)
in the file I have
![image](https://user-images.githubusercontent.com/28983495/126659952-31fcfa70-f1b3-4e92-87bf-f949d51e709d.png)

And the formatter setting are there
![image](https://user-images.githubusercontent.com/28983495/126659792-27c33963-cb0d-4b2d-bf20-34669da96fa5.png)

**Comment by PhilippSalvisberg** [comment]
The formatter settings are for sure not loaded properly. There must be something wrong with the setup.

Have you changed the right `product.conf`? What does the value for `dbtools.arbori.home` show under About -> Properties? Can you show me also the screenshot of the custom settings?

**Comment by adrianboangiu** [comment]
This was the problem. The custom settings were not loaded. I forced the import again and now it works.
Sorry to disturb you.

**Comment by PhilippSalvisberg** [comment]
Thanks for reporting back. I hope to get back to a single Arbori file in one of the future SQLDev versions.
