### ISSUE TITLE
Enhancement "Parantheses following functions/procedures definitions and calls" not working 

### ISSUE THREAD

**Issue by adrianboangiu** [Trivadis/plsql-formatter-settings#117]
Hello,
Using SQL Developer 21.2 (sqldeveloper-21.2.0.187.1842-x64) and the plsql-formatter-settings from 19.07.2021 I discover that the issue "Parantheses following functions/procedures definitions and calls" that has been closed is not working.
My preferences are 
![image](https://user-images.githubusercontent.com/28983495/126650054-f486b183-090e-46ed-b4d2-b042873c2e81.png)
Do I have to change something to make it work?
Thank you.

**Comment by PhilippSalvisberg** [comment]
When I format look at the cases described in https://github.com/Trivadis/plsql-formatter-settings/issues/99#issuecomment-810129673 then the results are the following with your settings:

```sql
-- 1 . Function definition (create or replace function)

CREATE OR REPLACE FUNCTION f(
   p1 IN INTEGER
) RETURN INTEGER IS
BEGIN
   RETURN 1;
END;
/

-- 2. Package and package body function declaration (function)

CREATE OR REPLACE PACKAGE pkg IS
   FUNCTION f(
      p1 IN INTEGER
   ) RETURN INTEGER;
END;
/

CREATE OR REPLACE PACKAGE BODY pkg IS
   FUNCTION f(
      p1 IN INTEGER
   ) RETURN INTEGER;
END;
/

-- 3. Package body function definition (function)

CREATE OR REPLACE PACKAGE BODY pkg IS
   FUNCTION f(
      p1 IN INTEGER
   ) RETURN INTEGER IS
   BEGIN
      RETURN 1;
   END;
END;
/

-- 4. Procedure definition (create or replace procedure)

CREATE OR REPLACE PROCEDURE p(
   p1 IN INTEGER
) IS
BEGIN
   NULL;
END;
/

-- 5. Package and package body procedure declaration (procedure)

CREATE OR REPLACE PACKAGE pkg IS
   PROCEDURE p(
      p1 IN INTEGER
   );
END;
/

CREATE OR REPLACE PACKAGE BODY pkg IS
   PROCEDURE p(
      p1 IN INTEGER
   );
END;
/

-- 6. Package body procedure definition (procedure)

CREATE OR REPLACE PACKAGE BODY pkg IS
   PROCEDURE p(
      p1 IN INTEGER
   ) IS
   BEGIN
      NULL;
   END;
END;
/

-- 7. Function call

SELECT f(1, 2, 3, 4, 5)
  FROM dual;

-- 8. Procedure call

BEGIN
   p(1, 2, 3, 4, 5);
END;
/

-- 9. Variable of type Cursor declaration

DECLARE
   CURSOR c1(
      p1 IN VARCHAR2
   ) IS
      SELECT col1
        FROM t
       WHERE col2 = p1;
BEGIN
   NULL;
END;
/

--- 10. Variable of type Cursor usage

BEGIN
   OPEN c2(1, 2, 3, 4, 5);
END;
/
```

This looks good IMO. What do you expect?

**Comment by adrianboangiu** [comment]
It is very strange that I obtain different results, but again I will give you examples using images.
I format files that contain package definition and package body. Whatever file I format I have the issue.
for example the package:
![image](https://user-images.githubusercontent.com/28983495/126658580-8ed43261-4478-479a-861b-ea2d89ae4af7.png)
and somewhere in the package body:
![image](https://user-images.githubusercontent.com/28983495/126658752-77161738-1fd3-4f57-a574-ecbe7b76f28d.png)

**Comment by PhilippSalvisberg** [comment]
I assume that the formatter settings are not configured correctly. Similar issue as in #116. The formatting result in your screen shot do not match the configured rules. 

I tried that in macOS and Windows. Works in both environments as expected.

Beside that the test cases for [aligned datatypes](https://github.com/Trivadis/plsql-formatter-settings/blob/main/tests/src/test/java/com/trivadis/plsql/formatter/settings/tests/rules/O8_align_datatypes.java) would have failed if this does not work. They expect no spaces between function name and the left parenthesis.

**Comment by adrianboangiu** [comment]
The problem was solved by reimporting the custom settings.
