### ISSUE TITLE
2 new lines inserted after IS in procedure/function definition

### ISSUE THREAD

**Issue by krokyk** [Trivadis/plsql-formatter-settings#12]
This happens when certain number of characters between IS and BEGIN is exceeded

```sql
    FUNCTION get_id1 (
        p_1  NUMBER,
        p_2  NUMBER,
        p_3  NUMBER
    ) RETURN NUMBER IS
        local_1  NUMBER;
        local_2  NUMBER;
        local_3  NUMBER;
        local_4  NUMBER;
        local_5  NUMBER;
    BEGIN
        RETURN 9999;
    END get_id1;

    FUNCTION get_id2 (
        p_1  my_table.id%TYPE,
        p_2  my_table.id%TYPE,
        p_3  my_table.id%TYPE
    ) RETURN my_table.id%TYPE IS

        local_1  my_table.id%TYPE;
        local_2  my_table.id%TYPE;
        local_3  my_table.id%TYPE;
        local_4  my_table.id%TYPE;
        local_5  my_table.id%TYPE;
    BEGIN
        -- some code
        RETURN 9999;
    END get_id2;
```

**Comment by PhilippSalvisberg** [comment]
I guess you are using different settings. With the latest settings for SQLDev 20.2 the result is the following:

```
   FUNCTION get_id1 (
      p_1  NUMBER,
      p_2  NUMBER,
      p_3  NUMBER
   ) RETURN NUMBER IS
      local_1  NUMBER;
      local_2  NUMBER;
      local_3  NUMBER;
      local_4  NUMBER;
      local_5  NUMBER;
   BEGIN
      RETURN 9999;
   END get_id1;
   FUNCTION get_id2 (
      p_1  my_table.id%TYPE,
      p_2  my_table.id%TYPE,
      p_3  my_table.id%TYPE
   ) RETURN my_table.id%TYPE IS
      local_1  my_table.id%TYPE;
      local_2  my_table.id%TYPE;
      local_3  my_table.id%TYPE;
      local_4  my_table.id%TYPE;
      local_5  my_table.id%TYPE;
   BEGIN
      -- some code
      RETURN 9999;
   END get_id2;
```

**Comment by krokyk** [comment]
Yes you are right, there are 2 settings I changed

1. indentation from 3 to 4 spaces (this alone doesn't make a difference)
2. and in Line Breaks - After statements changed from Single to Double Break

The (2) is essential as I want to have empty lines between individual functions and procedures. Once I change that, new line is added after IS

    
CREATE OR REPLACE PACKAGE BODY abc AS

    FUNCTION get_id1 (
        p_1  NUMBER,
        p_2  NUMBER,
        p_3  NUMBER
    ) RETURN NUMBER IS
        local_1  NUMBER;
        local_2  NUMBER;
        local_3  NUMBER;
        local_4  NUMBER;
        local_5  NUMBER;
    BEGIN
        RETURN 9999;
    END get_id1;

    FUNCTION get_id2 (
        p_1  my_table.id%TYPE,
        p_2  my_table.id%TYPE,
        p_3  my_table.id%TYPE
    ) RETURN my_table.id%TYPE IS

        local_1  my_table.id%TYPE;
        local_2  my_table.id%TYPE;
        local_3  my_table.id%TYPE;
        local_4  my_table.id%TYPE;
        local_5  my_table.id%TYPE;
    BEGIN
      -- some code
        RETURN 9999;
    END get_id2;

END;

Any suggestion how to achieve this?

**Comment by PhilippSalvisberg** [comment]
Thank you for the additional information. Now I can reproduce the behaviour.

The `brkX2_1` query handles that. This part of the expression is responsible for the additional, conditional line break:

```
| [node) is_or_as & [node+1) decl_list & [(node+1)+20 < (node+1)) -- long declarations
```

I'm going to change the behaviour as follows, if X2 is enabled:
- never add a new line after `as_or_is` for PL/SQL units
- add always a new line after `as_or_is` for a package specification or package body

**Comment by krokyk** [comment]
Thanks for this too. Going to try it soon.
