### ISSUE TITLE
Bad formating IN OUT parameters for procedures

### ISSUE THREAD

**Issue by wienerri** [Trivadis/plsql-formatter-settings#129]
Hi

After formating:
```sql
create or replace procedure dummy(
   A in
   out varchar2,
   b in
   out number
) is
--BEFORE EACH ROW
begin
   null;
end;
```
I assume something like 
```sql
create or replace procedure dummy(
   A in out varchar2,
   b in out number
) is
--BEFORE EACH ROW
begin
   null;
end;
```

**Comment by PhilippSalvisberg** [comment]
In this case I can use the "After formatting" case as input, right? 
And yes, I agree. The line break before `out` should be removed. Thanks for reporting this.

**Comment by wienerri** [comment]
You are right, you can use "after formatting" as test case.

Thank you very much.
