### ISSUE TITLE
Indent before SET

### ISSUE THREAD

**Issue by krokyk** [Trivadis/plsql-formatter-settings#13]
After formatting, first and last line are indented with 3 spaces. Should be 0. (Why not 4 when I have indent set to 4 spaces in the formatter settings?)

```sql
   SET ECHO OFF;

CREATE OR REPLACE PACKAGE BODY emp_mgmt AS

    FUNCTION hire (
        last_name      IN  VARCHAR2,
        job_id         IN  VARCHAR2,
        manager_id     IN  NUMBER,
        salary         IN  NUMBER,
        department_id  IN  NUMBER
    ) RETURN NUMBER IS
        new_empno NUMBER(16, 0);
    BEGIN
        --some code
        return(new_empno);
    END;

END emp_mgmt;
/

   SET ECHO ON
```

**Comment by PhilippSalvisberg** [comment]
I can reproduce it and used the settings as in #12. 

> Why not 4 when I have indent set to 4 spaces in the formatter settings?

Well, it's not an indentation, it's a right alignment. Here is another example:

```
SET ECHO OFF
SELECT *
  FROM dual;
````

When you format this, you see that the `SET` is right-aligned with `SELECT`. 

Responsible is the query `rightAlignments` in the Arbori program. The `SET` keyword is query criterion without further conditions. This leads to the right-alignment.

I'm going to fix that.
