### ISSUE TITLE
Different formats for function declarations

### ISSUE THREAD

**Issue by adrianboangiu** [Trivadis/plsql-formatter-settings#143]
Hello,

I am using the version 21.2.1.204 of SQL Developer and the last version of the formatter settings with the following settings:

I have found that the same function declaration will be formatted differently according to initial format. Here are 4 examples of different formattings of the same function declaration in a package definition:
1.
```
   FUNCTION getDateFromDMY(
      calendarDay   IN INTEGER,
      calendarMonth IN INTEGER,
      calendarYear  IN INTEGER
   ) RETURN DATE;
```
is formatted
```
   FUNCTION getDateFromDMY(
      calendarDay   IN INTEGER
    , calendarMonth IN INTEGER
    , calendarYear  IN INTEGER
   )RETURN DATE;
```
Note that the space in front of RETURN was deleted
2.
```
   FUNCTION getDateFromDMY(
      calendarDay   IN INTEGER,
      calendarMonth IN INTEGER,
      calendarYear  IN INTEGER
   )
   RETURN DATE;
```
is formated:
```
   FUNCTION getDateFromDMY(
      calendarDay   IN INTEGER
    , calendarMonth IN INTEGER
    , calendarYear  IN INTEGER
   )
      RETURN DATE;
```
3.
`FUNCTION getDateFromDMY( calendarDay IN INTEGER, calendarMonth IN INTEGER, calendarYear IN INTEGER ) RETURN DATE;
`
is formated:
```
   FUNCTION getDateFromDMY( calendarDay   IN INTEGER
                          , calendarMonth IN INTEGER
                          , calendarYear  IN INTEGER )RETURN DATE;
```
4.
```
   FUNCTION getDateFromDMY( calendarDay IN INTEGER, calendarMonth IN INTEGER, calendarYear  IN INTEGER )
   RETURN DATE;
```
is formatted:
```
   FUNCTION getDateFromDMY( calendarDay   IN INTEGER
                          , calendarMonth IN INTEGER
                          , calendarYear  IN INTEGER )
      RETURN DATE;
```
I don't know if it is normal to have different formattings for the same "object". I somehow expected to have all the time the 4rd formatting.

Can I have your opinion about it?
Best regards,
Adrian

**Comment by PhilippSalvisberg** [comment]
This is intentional. It was introduced with #105. See also this [blog post](https://www.salvis.com/blog/2021/07/18/lightweight-formatter-for-pl-sql-sql/).

**Comment by PhilippSalvisberg** [comment]
See also [this tweet](https://twitter.com/phsalvisberg/status/1406918272113590276?s=20) with a short audioless video demonstrating the lightweight formatter with `json_table`.

**Comment by PhilippSalvisberg** [comment]
Closed due to inactivity.
