### ISSUE TITLE
Enforce concise line separator logic (either LF or CRLF)

### ISSUE THREAD

**Issue by florian-caton** [Trivadis/plsql-formatter-settings#164]
Current version of `format.js` seems to use the default system line separator, is there a way to force it to another one ? 

I'm facing some weird results on Windows, working on Unix/Linux files : some line separators are modified by the formatter and some aren't. The resulting file ends up with mixed line separators. Using SqlDev, i can force it in the settings.

Something that could be included in the advanced_format.xml would be great.
For example  : 

```xml
<options>
   <lineSeparator>system-default|windows|unix|mac</lineSeparator>
</options>
```

**Comment by PhilippSalvisberg** [comment]
@florian-caton . I can reproduce your observation. The reason for the different behavior in SQLDev and SQLcl is that in SQLDev the result in presented in a Swing editor. The handling of new lines in such an editor is best described in https://docs.oracle.com/javase/8/docs/api/javax/swing/text/DefaultEditorKit.html and https://docs.oracle.com/javase/8/docs/api/javax/swing/text/DefaultEditorKit.html#EndOfLineStringProperty . 

The editor normalizes the result of the formatter. When serializing a document it uses the `EndOfLineStringProperty`. This is either CRLF or LF. All lines will have the same line separator when written to disk. 

The logic used by the editor is a bit different to that what I've described above. If a CRLF is found in the input (file) then the `EndOfLineStringProperty` is set to CRLF.

As a result when opening file with mixed line separators, the content will be recognized as Windows file (shown at the right bottom in SQLDev). As soon as the file is saved it will have consistent line separators. All CRLF.

**Comment by PhilippSalvisberg** [comment]
I think mimicking the logic of https://docs.oracle.com/javase/8/docs/api/javax/swing/text/DefaultEditorKit.html#EndOfLineStringProperty to determine the line separator.

**Comment by florian-caton** [comment]
I'm fine with that.
Again, thanks a lot for your fast analysis, and even more for fixing it so fast.
