### ISSUE TITLE
Installation problem - SQL Developer

### ISSUE THREAD

**Issue by pauljereb** [Trivadis/plsql-formatter-settings#185]
I followed the 11 steps to install the formatter settings in SQL Developer.

While everything looks fine after uploading the .xml
![ScreenshotAdvancedFormat](https://user-images.githubusercontent.com/50493018/148750576-e2d62982-bca4-4386-bfc3-affd5259e5e7.png)

things seem to get messed up after uploading the .arbori
![ScreenshotCustomFormat](https://user-images.githubusercontent.com/50493018/148750596-48f97fc0-048d-4b9e-a43d-3914a334af51.png)

When formatting a random file using Ctrl-F7, the result looks like in the screenshot above (no formatting, removed line-breaks etc.).

I tried this on fresh installations of SQL Developer 21.4.1 with the same result on both Windows and MacOS.

Am I missing something?

**Comment by PhilippSalvisberg** [comment]
I guess you are using a JDK 8. SQLDev 20.4.x does not work properly with JDK 8. See also #171 and https://community.oracle.com/tech/developers/discussion/4492626/arbori-javascript-callback-functions-do-not-work-in-sqldev-21-4-0-21-4-1-with-jdk8-why .
