### ISSUE TITLE
Could you add 'format file file_input file_output' command and daemon (pipeline) mode?

### ISSUE THREAD

**Issue by NisSAM** [Trivadis/plsql-formatter-settings#195]
This is an enhancement  request.
It would be great if we could run standalone tvdformat and pass commands like `format file file_input file_output` to it one after the other. Currently, we can emulate this mode by starting a new dvdformat for each new file to be processed. But it takes some time to start the new tvdformat for each file.
We can't use batch (<rootPath> as a directory) mode since we don't have all the files in advance. They are processed in pipeline mode.

**Comment by PhilippSalvisberg** [comment]
If you do not want to change the original file you can copy it and format the copy. There are no plans to build a daemon process to overcome the startup times. An alternative is a native image which start much faster and is simpler to use.

**Comment by PhilippSalvisberg** [comment]
>We can't use batch ( as a directory) mode since we don't have all the files in advance.

I'd be interested to hear more. Why exactly don't you have access to all the files to be formatted so you can process them in one go?

**Comment by PhilippSalvisberg** [comment]
Closed due to inactivity.
