### ISSUE TITLE
Line breaks after SELECT but not after FROM and WHERE

### ISSUE THREAD

**Issue by vitodcampanelli** [Trivadis/plsql-formatter-settings#235]
I am using SQL Developer 22.2.1.234 and I was curious to know if it was possible to apply the following format condition.

We would like to have a line break after SELECT but not after the FROM and WHERE. The option in SQL Developer applies to all three.

<img width="314" alt="image" src="https://user-images.githubusercontent.com/12102777/190169069-4fcfcd3e-bb7c-434f-9241-bcb2780a8ccf.png">

If there a way to achieve this? If this is not the correct place to ask the question, then please delete the issue/question.

Thanks

**Comment by PhilippSalvisberg** [comment]
I have not tried with 22.2.1 yet. It works with 22.2.0.

Unformatted:

```sql
select * from dual where dummy = 'X';
```

Formatter result:

```sql
select
   *
from
   dual
where
   dummy = 'X';
```

Can you please provide the input you've tried, the formatter settings you've used the effective and the expected result? Thank you.

**Comment by vitodcampanelli** [comment]
Thank you for the reply. This use case might not be possible with the standard SQL Developer preferences, but I just wanted to see before trying to understand the Arbori syntax.

## Unformatted
```sql
select 1, 2, 3
from dual
where 1 = 1 and 2 = 2;
```

## Formatter Results
```sql
select 1,
       2,
       3
from dual
where 1 = 1
      and 2 = 2;
```

## Expected Results
```sql
select
  1,
  2,
  3
from dual
where 1=1
  and 2=2;
```

Here are my SQL Developer Advanced Format settings

<img width="556" alt="image" src="https://user-images.githubusercontent.com/12102777/190187280-b203fa05-b3fb-46c1-ab42-51c1be5bbff8.png">

**Comment by PhilippSalvisberg** [comment]
Thanks. I can reproduce your results. 

With the current settings it is not possible to produce your expected result. I see two problems:

1. You do not want to have keywords right-aligned, but the `and` should be right-aligned with `where`.
     It's an unusual formatting style and not covered by the settings nor in the Arbori program. However, you can achieve what you want by adapting the Arbori program.

2. You just want to a line break after `select` but not after `from` and `where`.
    The option is for all keywords (e.g. also for the `order by`) and not just for the `select`. There is no option for that in SQLDev. However, it's doable, but you have to adapt the Arbori program yourself.

I hope this answers your question.

**Comment by PhilippSalvisberg** [comment]
>1. You do not want to have keywords right-aligned, but the and should be right-aligned with where.
>It's an unusual formatting style and not covered by the settings nor in the Arbori program. However, you can achieve what >you want by adapting the Arbori program

Correction. It's just indented by 2 spaces, not right-aligned.

I guess it's probably the easiest to check `SELECT/FROM/WHERE` and write an Arbori fix-rule at the end that removes the line break and indentation for the first `select_term` and fixes the indentation for all other `select_term`.

**Comment by vitodcampanelli** [comment]
Thank you, I am not very familiar with the Arbori rules, so I will take a look. Please go ahead and close this issue.

**Comment by PhilippSalvisberg** [comment]
To produce the expected result you can change the Arbori queries `o6_select_before` and `o6_select_after` like that:

```
o6_select_before:
      [parent) subquery
    & (
        [node) 'SELECT'
      )
    & parent < node
;

o6_select_after:
      [parent) subquery
    & (
        [node) 'SELECT'
      )
    & parent < node
;
```

These queries provide the node for the option `SELECT/FROM/WHERE`. In this case it considers only `SELECT` and all other keywords like `WITH`, `INTO`, `FROM`, `WHERE`, `CONNECT`, `START`, `GROUP`, `HAVING`, `ORDER` are ignored.

I suggest to change the Arbori program in an external editor and not in the preferences dialog.

**Comment by vitodcampanelli** [comment]
That is fantastic, it worked. I will play with the Arbori program to help resolve the issue with break after commas in select list. FROM and WHERE clause work with your example.

```sql
select
  1, 2, 3
from dual
where 1 = 1
  and 2 = 2;
```

**Comment by PhilippSalvisberg** [comment]
This is a lightweight formatter. 

So, if you add a line break in one of the select terms, the result is as you expect. 

If you want to enforce every `select_term` an a new line then have a look at the JS in the Arbory query `a16_add_line_breaks_before`. Especially this [if statement](https://github.com/Trivadis/plsql-formatter-settings/blob/sqlcl-22.2.1/settings/sql_developer/trivadis_custom_format.arbori#L2503). You might want to comment it out.
