### ISSUE TITLE
Are You aware of

### ISSUE THREAD

**Issue by gassenmj** [Trivadis/plsql-formatter-settings#242]
Hi Philipp,

great work! Love the repo!

i am aware that the current readme states that SQLcl 22.4 is not yet supported. 
Opening an issue anyway - feel free to close it.

It seems that running the `format.js` script fails when using SQLcl 22.4.

Is it only my setup?

Many thanks in advance!

```
.../orcl/sqlcl/plsql-formatter-settings-main/sqlcl () >ll
total 80
drwxrwxr-x@ 12 xxx  staff   384B Dec 14 15:44 ..
drwxrwxr-x@  4 xxx  staff   128B Nov 12 13:22 .
-rw-rw-r--@  1 xxx  staff   7.8K Nov 12 13:22 README.md
-rw-rw-r--@  1 xxx  staff    32K Nov 12 13:22 format.js
.../orcl/sqlcl/plsql-formatter-settings-main/sqlcl () >sql


SQLcl: Release 22.4 Production on Fri Jan 06 10:51:20 2023

Copyright (c) 1982, 2023, Oracle.  All rights reserved.

@ > script format.js
!ScriptCommand.1!@ > tvdformat

Error starting at line : 1 in command -
tvdformat
Error report -
Unknown Command

@ > 
```

**Comment by PhilippSalvisberg** [comment]
Hi @gassenmj,

It should work with SQLcl 22.4.

According your error message I guess that you a are using a Java version without a JavaScript engine. Java version newer than 11 do not include Nashorn anymore. Hence no JavaScript can be executed from SQLcl. The best thing would be  to enhance SQLcl and distribute it with a Nashorn compatible JavaScript engine.

The easiest solution for now is to ensure that the JAVA_HOME points to a JDK11 before calling SQLcl.

Hope this helps.

**Comment by gassenmj** [comment]
argh `rtfm` :D You even documented it. Thanks for Your help! It worked.
