### ISSUE TITLE
formatting large files with repetitive statements, i.e. insert

### ISSUE THREAD

**Issue by plamen-ppv** [Trivadis/plsql-formatter-settings#244]
Hi again!

I have some SQL files which contain large number (hunderds or thousands) of INSERT statements. It is not unusual to use SQL Developer to export the content of a table to insert statements. I even have an example of Oracle's demo APEX Interactive Grid app which has a stored procedure with >4000 insert statements. Formatting such sql file doesn't work... SQLcl just hangs. This is not a problem of your tool, but it might be nice if you can add some logic to format.js or to the arbori script to skip such files. 

Best regards,
Plamen

**Comment by PhilippSalvisberg** [comment]
Hi @plamen-ppv 

Right, there are some SQL constructs which are slow to process and may fail when running from SQLcl. There are two workarounds:

a) use the standalone formatted `tvdformat.jar`. It's still slow, but it usually finishes (not feasible for interactive usage)
b) exclude the files from processing via the an [ignore](https://github.com/Trivadis/plsql-formatter-settings/tree/main/sqlcl#using-an-ignore-file) configuration . I use this approach in various projects where I format the code via pre-commit hook. You could also create a batch-file so you do not have to pass the `ignore` parameter each time. 

I do not see an easy way to identify problematic files. It is not always the size. Also, very large lists (`in` or type constructors) are problematic, even if the file is small. So using the `ignore` parameter seems to be the best approach IMO.

**Comment by PhilippSalvisberg** [comment]
If the root cause of the slow Arbori queries cannot be addressed an option could be to define a timeout option with a default value of let's say 10 seconds per file. If the timeout is reached the formatting process for the current file could be aborted.

**Comment by plamen-ppv** [comment]
Adding such timeout option will be the most pragmatic solution! it will cover all cases, regardless of origin.
