### ISSUE TITLE
Package constant formatting

### ISSUE THREAD

**Issue by Gepar** [Trivadis/plsql-formatter-settings#249]
I think global constant in packages should format like parameters inside functions (with same shift and with same registry).
<img width="490" alt="image" src="https://user-images.githubusercontent.com/5103892/230790124-1a4c2db9-9577-4642-82df-a79c4f37ecfa.png">
Not like this
<img width="450" alt="image" src="https://user-images.githubusercontent.com/5103892/230790137-ce59e096-2a61-4cfc-a746-e64589936aa4.png">
Sorry if issue section only for issues in project and not in formatting style.
I tried to find any rules about global constants in arbori file by myself but no luck.

**Comment by PhilippSalvisberg** [comment]
Thanks @Gepar  for reporting this issue. I can reproduce it with the default settings and this input that is also the output:

```sql
create or replace package x as
   co_aaaa constant char := 'a';
   co_b constant char := 'b';
   co_cccccccccc constant char := 'c';
end;
/

create or replace package body x as
   co_aaaa       constant char := 'a';
   co_b          constant char := 'b';
   co_cccccccccc constant char := 'c';
end;
/
```

expected would be something like this:

```sql
create or replace package x as
   co_aaaa       constant char := 'a';
   co_b          constant char := 'b';
   co_cccccccccc constant char := 'c';
end;
/

create or replace package body x as
   co_aaaa       constant char := 'a';
   co_b          constant char := 'b';
   co_cccccccccc constant char := 'c';
end;
/
```

Please note that constants are properly aligned in the package body.
