### ISSUE TITLE
Comment indentation and new lines (or lack of them)

### ISSUE THREAD

**Issue by krokyk** [Trivadis/plsql-formatter-settings#25]
Settings:
![image](https://user-images.githubusercontent.com/15148711/89173122-10a6fd00-d584-11ea-82b9-5566764156be.png)

Source:
```sql
DECLARE
    TYPE arr IS
        VARRAY(20) OF VARCHAR2(1) NOT NULL;

-- some comment
my_arr arr := arr(
    'a',
    'b',
    'c',
    'd',
    'e'
);
BEGIN
    NULL;
END;
/

CREATE OR REPLACE PACKAGE BODY my_pkg AS
    TYPE arr IS
        VARRAY(20) OF VARCHAR2(1) NOT NULL;

my_arr arr := arr(
    'a',
    'b',
    'c',
    'd',
    'e'
);
END;
/
```

Before/After comparison:
![image](https://user-images.githubusercontent.com/15148711/89173061-f1a86b00-d583-11ea-8d91-4592e1c0705d.png)

**Comment by PhilippSalvisberg** [comment]
## Indentation of comments

The indentation is never changed. There is one exception. When you set "Line Breaks Before line comments". In this case, after processing the Arbori programm, the post-processor in SQLDev's formatter adds a new line with some indentation (which is not always correct).

It's not foreseen in SQLDev to format comments. Comments are not part of provided parse-tree. Therefore you cannot query them with Arbori. Of course there are options (where you do the parsing yourself). But for the time being comment indentation handling is not a provided feature. You can place one or more comments before and after every single token. Formatting them without a proper context (provided by a parse-tree) is very very challenging. 

As a result all requests/issues regarding comments are rejected. Comments are processed with the default logic of SQL Developer. If you'd like to change that, then I suggest to submit a change request for SQL Developer or discuss it in the SQL Developer's forum.

## Empty Lines

The preference is called internally `extraLinesAfterSignificantStatements`. So the name in the UI `Line Breaks After statements` is a bit misleading.

The Query `brkX2` defines the "significant" statements. I understand that it is wanted to add an empty line after "as/is" for a package or package body to separate the the first unit like the subsequent ones. But for the declare section in general? If you do that then you should also add a new line after the "as/is" of a function/procedure, right? 

I'm not ready to change that. 

However, If you want to add it in your Arbori file variant. Look for `brkX2_1` and this line:

```
| [node) 'DECLARE'
```

BTW: the `brkX2` query is also responsible to identify the statements where an empty line is preserved (beside empty lines around comments).

However, I agree that the current definition might not be consistent (e.g. an empty line is added before  `END` of a package but not before the end of a package body). But these would be separate issues.

Therefore I close this issue.

**Comment by krokyk** [comment]
Fair enough :) Re empty line, I actually don't like the empty line after that package body (i.e. on line 19 in that comparison screenshot) and I would prefer not having it, just like after the declare. So for my purposes I just commented out this line from arbori:

    -- | [node) is_or_as & ([node^) pkg_body | [node^) pkg_spec)  -- salvisberg: added to solve issue #12 unconditional break after is_or_as of pkg_body/pkg_spec

**Comment by PhilippSalvisberg** [comment]
Yes, a lot of personal preferences are involved here. 

Therefore I would like to switch back to "Preserver Original" as default as soon as the remaining problems (wrong indent, unwanted new lines) are solved.  This requires corrections in the SQLDev code, which means that this will not be before 20.3.

With "Preserve Original" it would be nice to be able to add more optional empty lines. Based on this we could declare some additional "significant" statements. The side effect would be that "Double break" becomes less attractive.
