### ISSUE TITLE
Concatenation Bars being split apart invalidating strings

### ISSUE THREAD

**Issue by Samccull-Bunnings** [Trivadis/plsql-formatter-settings#257]
Based on the character count in a line the Abs bars can be split into separate lines which makes the code invalid
E.G.
![image](https://github.com/Trivadis/plsql-formatter-settings/assets/94417348/4eae9c89-b08a-4eb3-bbc0-64533776e371)
becomes
![image](https://github.com/Trivadis/plsql-formatter-settings/assets/94417348/6f0b04e2-399b-4b16-93cb-dfe6f2a42af4)

(attached a text file copy for reference)
[file.txt](https://github.com/Trivadis/plsql-formatter-settings/files/13608459/file.txt)

**Comment by PhilippSalvisberg** [comment]
I used the SQL Developer 23.1 and the following formatter settings

![image](https://github.com/Trivadis/plsql-formatter-settings/assets/3883171/d68f6d45-149c-408f-8e2b-506e1d6fd462)

to format your provided file (you know you can embedd it in Markdown):

```sql
begin
   DBMS_OUTPUT.put_line('wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww' || 'wwwwww');
end;
```

and the formatter result is

```sql
begin
   DBMS_OUTPUT.put_line('wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww' ||
   'wwwwww');
end;
```

Which looks good.

Could you please let me know the following things to make the issue reproducible:

- SQL Developer version
- OS and version
- Advanced Format Settings in SQL Developer

Thank you.

**Comment by PhilippSalvisberg** [comment]
I can reproduce the issue when using the [trivadis_advanced_format.xml](https://github.com/Trivadis/plsql-formatter-settings/blob/main/settings/sql_developer/trivadis_advanced_format.xml) and by using the default Arbori program provided by the SQL Developer team.

![image](https://github.com/Trivadis/plsql-formatter-settings/assets/3883171/8135fedb-f0c3-4d90-afad-8ea41450fe67)

I cannot reproduce it with the Arbori program provided in this repository ([trivadis_custom_format.arbori](https://github.com/Trivadis/plsql-formatter-settings/blob/main/settings/sql_developer/trivadis_custom_format.arbori). 

I kindly ask you to seek help in the SQL Developer forum regarding issues with the default Arbori program. Thank you.
