### ISSUE TITLE
Question: Formatting CREATE TABLE w/ CONSTRAINT

### ISSUE THREAD

**Issue by krokyk** [Trivadis/plsql-formatter-settings#27]
Unformatted source:
```sql
CREATE TABLE configuration (
    id              NUMBER NOT NULL,
    namespace       VARCHAR2(64 CHAR) NOT NULL,
    key             VARCHAR2(128 CHAR) NOT NULL,
    owner           VARCHAR2(256 CHAR),
    scope           VARCHAR2(256 CHAR),
    CONSTRAINT c$pk PRIMARY KEY (id),
    CONSTRAINT c$un_1 UNIQUE (id, namespace, key, owner, scope),
    CONSTRAINT c$un_2 UNIQUE (namespace, key, owner, scope)
);
```
What I get after formatting:
```sql
CREATE TABLE configuration (
    id         NUMBER NOT NULL,
    namespace  VARCHAR2(64 CHAR) NOT NULL,-- where is this double space between name and type coming from? is it configurable? maybe I always want 4 spaces between, or maybe I want one tab there (i.e. 1-4 spaces)
    key        VARCHAR2(128 CHAR) NOT NULL,
    owner      VARCHAR2(256 CHAR),
    scope      VARCHAR2(256 CHAR),
    CONSTRAINT c$pk PRIMARY KEY ( id ), --keep because <= 4 args and no spaces inside parentheses
    CONSTRAINT c$un_1 UNIQUE ( id,            --split because >4 args but just like inside some proc/function call. i.e. all args on their own line,
                               namespace,     --not keeping first on the constraint line and not having last combined with parenthesis
                               key,
                               owner,
                               scope ), 
                                        
    CONSTRAINT c$un_2 UNIQUE ( namespace,
                               key,
                               owner,
                               scope ) --keep because <= 4 args and no spaces inside parentheses
);
```
So basically I want to achieve this:
```sql
CREATE TABLE configuration (
    id          NUMBER NOT NULL,
    namespace   VARCHAR2(64 CHAR) NOT NULL,
    key         VARCHAR2(128 CHAR) NOT NULL,
    owner       VARCHAR2(256 CHAR),
    scope       VARCHAR2(256 CHAR),
    CONSTRAINT c$pk PRIMARY KEY (id),
    CONSTRAINT c$un_1 UNIQUE (
        id,
        namespace,
        key,
        owner,
        scope
    ),
    CONSTRAINT c$un_2 UNIQUE (namespace, key, owner, scope)
);
);
```

Any advice?

**Comment by PhilippSalvisberg** [comment]
> Any advice?

I assume you'd like to fix that in the Arbori program yourself, right?

In this case i suggest to look at the code outline in SQLDev. It will reval that you are dealing with `column` or `identifier` that are not `arg` nor `expr`. Hence this is not related with #19. 

The responsible condition for the line break is 

```
| :breaksAfterComma &  ([node+1) expr  | [node+1) column)               & [node) ',' 
                             & ![node^) aggregate_function & ![node^) analytic_function
                             -- & ... -- unable to keep (x,y) inline without referring to ancestor  
```

So you have to move the relevant part from the query `_extraBrkAfter` and `_extraBrkBefore` to `simpleIndentConditions`. This should do the trick. But be aware of side effects. `column` is also used in select statements... so maybe extending the existing conditions and adding a new, very specific one for constraints under `simpleIndentConditions` is better.

IMO everything not used in code (view, trigger, function, procedure, package, type) has low priority. My advice is. Live with the default formatting capabilities. Format it manually. 

Does this answer your question?

**Comment by PhilippSalvisberg** [comment]
>where is this double space between name and type coming from? 

From the `paddedIdsInScope` Java callback function in SQLDev.

>is it configurable? 

No.

**Comment by krokyk** [comment]
Hmm, being a developer, I would definitely give it a try. So... how does one actually efficiently "code" in arbori using SQL Developer? Any pointers are welcome. I know this is not the optimal place to ask this but I know of none other. I only found [this pdf ](https://vadimtropashko.files.wordpress.com/2017/02/arbori-starter-manual.pdf) which I'm reading through right now so any know-how from you is appreciated

**Comment by PhilippSalvisberg** [comment]
https://github.com/Trivadis/plsql-formatter-settings#links

**Comment by PhilippSalvisberg** [comment]
Let me know if you have questions. Would be nice to accept PRs in the future.

**Comment by PhilippSalvisberg** [comment]
If you have general questions regarding Arbori, then the [SQL Developer Forum](https://community.oracle.com/community/groundbreakers/database/developer-tools/sql_developer) ist a good place to ask them. 

If it's related to these formatter settings then you may open an issue (question) here as well.

**Comment by PhilippSalvisberg** [comment]
Does this answer your question?

**Comment by krokyk** [comment]
Yes :) Re PRs, I cannot promise anything, formatting is a low priority in our project so I guess I would have to sacrifice some free time to do it. But I would definitely like to unify this as there's a lot of mess since 20 devs are working on project and SQL is just a small part. But everyone has a slightly different taste or they don't care at all so introducing one magic key combination that would do the trick is something to think about.
