### ISSUE TITLE
keyword return  is not uppercased

### ISSUE THREAD

**Issue by wienerri** [Trivadis/plsql-formatter-settings#45]
BEGIN
   return;
END;
/

I think return is a keyword and should be uppercased.

**Comment by PhilippSalvisberg** [comment]
Right. `RETURN` is a keyword. However, Oracle's parser identifies it in this context as an `identifier` and `name` and `name_wo_function_call` and `procedure_call`. You see that in the code outline:

![image](https://user-images.githubusercontent.com/3883171/90531475-654a9a80-e176-11ea-8164-0cb3aa925abc.png)

Therefore the parser does not treat `return` as a keyword and does not change the case. The "serializer" component as I've called it in [this blog post](https://www.salvis.com/blog/2020/04/13/formatting-code-with-sql-developer/) is responsible for changing the case of keywords. It's not in the designed scope of the Arbori program to handle that. Of course you have access to the source and can manipulate it the way you want. In this scenario you would need to change the setting to "Keep unchanged" and then do the the complete keyword processing yourself. You need to process the parse-tree to deal with cases such as this one:

```
SELECT dummy AS return
  FROM dual;
```

Yes `RETURN` is a keyword, but would you want to change it to upper-case in this context? Some might say yes, some might say no.

If you want to change that behaviour I suggest to ask the SQL Developer team in the [SQL Developer forum](https://community.oracle.com/community/groundbreakers/database/developer-tools/sql_developer), if they can fix that.

I'd like to keep the responsibility of the keyword handling as is. Therefore I close this issue.
