### ISSUE TITLE
Format SQL code blocks in markdown files

### ISSUE THREAD

**Issue by PhilippSalvisberg** [Trivadis/plsql-formatter-settings#51]
The idea is to find all SQL code blocks in [Markdown files](https://guides.github.com/features/mastering-markdown/)

- starting with <code>```sql</code> (optionally with whitespace between the last backtick and `sql`) and
- ending with <code>```</code> 

and format them with the chosen settings.

I see two options to implement that feature

1. just add the `.md` file extension to the default list of files to be processed and hard-code the behavior for the processing of `.md` files.
2. add an additional option (e.g. `mext=`) to identify markdown file extensions. Only files with these extensions are processed as markdown files. The default file extensions could be `.markdown, .mdown, .mkdn, .md`(see https://github.com/github/markup#markups). So, to avoid the processing of markdown files `mext=` (empty list) must be passed. To process markdown files only `ext=` must be passed.

In both cases markdown files are processed by default. I'm in favor of option two, because it's more flexible.

**Comment by elizabethwanjiku703** [comment]
Very helpful. Thank you
