### ISSUE TITLE
comma before - merge statement is strange formated

### ISSUE THREAD

**Issue by wienerri** [Trivadis/plsql-formatter-settings#68]
Hi,
 I use "on comma before" setting
1) When I format merge statement, I have got a few stange things - sometimes there are line break after comma (every 3th line in "select" part, approximately about 9th line in "values" part. This error occured only in "on comma before" setting.
2) There is unwanted line break after ")" but before alias "d"
3) After end of USING section formating work strange, all lines are shifted at the start of line since INSERT section started. 
When I use comma after, it looks slightly better, but still ON keyword is shifted at the start of line.
It lookls like formater didn't understand, that this is ONE statement and format section as independent statements.

Example: 
MERGE INTO tcp_pol_agent_commission_no c
USING (
         SELECT DISTINCT a2.name_id_no -- name_id_no number 22 N Agent identifier
                        ,a2.commission_no -- commission_no number 22 N Commission number
                        ,a2.TIMESTAMP -- timestamp date 7 Y Date and time for last insert/update of the record                                                                                            
                        ,
                        a2.userid -- userid varchar2 8 Y Identification of the user who last inserted/updated the record
                        ,a2.record_version -- record_version number 22 Y Updated whenever a record is inserted/updated to ensure locking
                        ,a2.superordinate_no -- superordinate_no number 22 Y                                                                      
                        ,
                        a2.legal_form -- legal_form varchar2 2000 Y 
                        ,a2.start_date -- start_date date 7 Y 
                        ,a2.end_date -- end_date date 7 Y                                               
                        ,
                        a2.location_id_no -- location_id_no number 22 Y 
                        ,a2.sellerpid -- sellerpid number 22 Y 
                        ,a2.ag_channel -- ag_channel number 22 Y Kanál obchodníka - viz XLA_REFERENCE(AGENT_CHANNEL).                       
                        ,
                        a2.companyid$$ -- companyid$$ number 22 Y 
                        ,a2.agency -- agency varchar2 3 N 
                        ,a2.com_group -- com_group varchar2 2 N                        
                        ,
                        a2.level_code -- level_code number 22 Y 
                        ,a2.distribution -- distribution varchar2 2 Y 
           FROM tcp_pol_agent_commission_no@rwie_mig_vias
           a2
               ,tcp_mig_vias_m11_adrpol r
          WHERE r.role_cislo = 7
            AND to_number(r.role_id) = a2.commission_no
      )
d ON ( c.commission_no = d.commission_no )
WHEN MATCHED THEN UPDATE
SET start_date = d.start_date
,end_date = d.end_date
WHEN NOT MATCHED THEN
INSERT (
   name_id_no
   ,commission_no
   ,TIMESTAMP
   ,userid
   ,record_version
   ,superordinate_no
   ,legal_form
   ,start_date
   ,end_date
   ,location_id_no
   ,sellerpid
   ,ag_channel
   ,companyid$$
   ,agency
   ,com_group
   ,level_code
   ,distribution )
VALUES
   ( 629021949 -- d.name_id_no -- name_id_no number 22 N Agent identifier
   ,d.commission_no -- commission_no number 22 N Commission number
   ,d.TIMESTAMP -- timestamp date 7 Y Date and time for last insert/update of the record
   ,d.userid -- userid varchar2 8 Y Identification of the user who last inserted/updated the record
   ,d.record_version -- record_version number 22 Y Updated whenever a record is inserted/updated to ensure locking
   ,d.superordinate_no -- superordinate_no number 22 Y 
   ,d.legal_form -- legal_form varchar2 2000 Y 
   ,d.start_date -- start_date date 7 Y    
   ,
   d.end_date -- end_date date 7 Y 
   ,d.location_id_no -- location_id_no number 22 Y 
   ,d.sellerpid -- sellerpid number 22 Y 
   ,d.ag_channel -- ag_channel number 22 Y Kanál obchodníka - viz XLA_REFERENCE(AGENT_CHANNEL).
   ,d.companyid$$ -- companyid$$ number 22 Y 
   ,d.agency -- agency varchar2 3 N 
   ,d.com_group -- com_group varchar2 2 N 
   ,d.level_code -- level_code number 22 Y 
   ,d.
   distribution -- distribution varchar2 2 Y     
   /* */ );

**Comment by PhilippSalvisberg** [comment]
In SQLDev 20.2 the linesize calculation is buggy and leads to unwanted line breaks in various situation. See also https://community.oracle.com/tech/developers/discussion/4341424/formatting-issue-unwanted-line-break-after-long-single-line-statement-bug .

As a workaround you can set a ridiculous max line size. I've set it to 2000 to produce the following result (which is better IMO):

```sql
MERGE INTO tcp_pol_agent_commission_no c
USING (
         SELECT DISTINCT a2.name_id_no -- name_id_no number 22 N Agent identifier
                       , a2.commission_no -- commission_no number 22 N Commission number
                       , a2.TIMESTAMP -- timestamp date 7 Y Date and time for last insert/update of the record
                       , a2.userid -- userid varchar2 8 Y Identification of the user who last inserted/updated the record
                       , a2.record_version -- record_version number 22 Y Updated whenever a record is inserted/updated to ensure locking
                       , a2.superordinate_no -- superordinate_no number 22 Y
                       , a2.legal_form -- legal_form varchar2 2000 Y
                       , a2.start_date -- start_date date 7 Y
                       , a2.end_date -- end_date date 7 Y
                       , a2.location_id_no -- location_id_no number 22 Y
                       , a2.sellerpid -- sellerpid number 22 Y
                       , a2.ag_channel -- ag_channel number 22 Y Kanál obchodníka - viz XLA_REFERENCE(AGENT_CHANNEL).
                       , a2.companyid$$ -- companyid$$ number 22 Y
                       , a2.agency -- agency varchar2 3 N
                       , a2.com_group -- com_group varchar2 2 N
                       , a2.level_code -- level_code number 22 Y
                       , a2.distribution -- distribution varchar2 2 Y
           FROM tcp_pol_agent_commission_no@rwie_mig_vias a2
              , tcp_mig_vias_m11_adrpol r
          WHERE r.role_cislo = 7
            AND to_number(r.role_id) = a2.commission_no
      )
d ON ( c.commission_no = d.commission_no )
WHEN MATCHED THEN UPDATE
SET start_date = d.start_date
, end_date = d.end_date
WHEN NOT MATCHED THEN
INSERT (
   name_id_no
   , commission_no
   , TIMESTAMP
   , userid
   , record_version
   , superordinate_no
   , legal_form
   , start_date
   , end_date
   , location_id_no
   , sellerpid
   , ag_channel
   , companyid$$
   , agency
   , com_group
   , level_code
   , distribution )
VALUES
   ( 629021949 -- d.name_id_no -- name_id_no number 22 N Agent identifier
   , d.commission_no -- commission_no number 22 N Commission number
   , d.TIMESTAMP -- timestamp date 7 Y Date and time for last insert/update of the record
   , d.userid -- userid varchar2 8 Y Identification of the user who last inserted/updated the record
   , d.record_version -- record_version number 22 Y Updated whenever a record is inserted/updated to ensure locking
   , d.superordinate_no -- superordinate_no number 22 Y
   , d.legal_form -- legal_form varchar2 2000 Y
   , d.start_date -- start_date date 7 Y
   , d.end_date -- end_date date 7 Y
   , d.location_id_no -- location_id_no number 22 Y
   , d.sellerpid -- sellerpid number 22 Y
   , d.ag_channel -- ag_channel number 22 Y Kanál obchodníka - viz XLA_REFERENCE(AGENT_CHANNEL).
   , d.companyid$$ -- companyid$$ number 22 Y
   , d.agency -- agency varchar2 3 N
   , d.com_group -- com_group varchar2 2 N
   , d.level_code -- level_code number 22 Y
   , d.distribution -- distribution varchar2 2 Y
/* */ );
``` 

I see the following issues:

- the alias `d` on line 25 should be on line 24, line break should occur on `ON`
- no indentation after `WHEN ... MATCHED THEN` after line 26 and 29
- no indentation on line 28

So the formatted result should look like this:

```sql
MERGE INTO tcp_pol_agent_commission_no c
USING (
         SELECT DISTINCT a2.name_id_no -- name_id_no number 22 N Agent identifier
                       , a2.commission_no -- commission_no number 22 N Commission number
                       , a2.TIMESTAMP -- timestamp date 7 Y Date and time for last insert/update of the record
                       , a2.userid -- userid varchar2 8 Y Identification of the user who last inserted/updated the record
                       , a2.record_version -- record_version number 22 Y Updated whenever a record is inserted/updated to ensure locking
                       , a2.superordinate_no -- superordinate_no number 22 Y
                       , a2.legal_form -- legal_form varchar2 2000 Y
                       , a2.start_date -- start_date date 7 Y
                       , a2.end_date -- end_date date 7 Y
                       , a2.location_id_no -- location_id_no number 22 Y
                       , a2.sellerpid -- sellerpid number 22 Y
                       , a2.ag_channel -- ag_channel number 22 Y Kanál obchodníka - viz XLA_REFERENCE(AGENT_CHANNEL).
                       , a2.companyid$$ -- companyid$$ number 22 Y
                       , a2.agency -- agency varchar2 3 N
                       , a2.com_group -- com_group varchar2 2 N
                       , a2.level_code -- level_code number 22 Y
                       , a2.distribution -- distribution varchar2 2 Y
           FROM tcp_pol_agent_commission_no@rwie_mig_vias a2
              , tcp_mig_vias_m11_adrpol r
          WHERE r.role_cislo = 7
            AND to_number(r.role_id) = a2.commission_no
      ) d 
ON ( c.commission_no = d.commission_no )
WHEN MATCHED THEN 
   UPDATE
      SET start_date = d.start_date
        , end_date = d.end_date
WHEN NOT MATCHED THEN
   INSERT (
      name_id_no
      , commission_no
      , TIMESTAMP
      , userid
      , record_version
      , superordinate_no
      , legal_form
      , start_date
      , end_date
      , location_id_no
      , sellerpid
      , ag_channel
      , companyid$$
      , agency
      , com_group
      , level_code
      , distribution )
   VALUES
      ( 629021949 -- d.name_id_no -- name_id_no number 22 N Agent identifier
      , d.commission_no -- commission_no number 22 N Commission number
      , d.TIMESTAMP -- timestamp date 7 Y Date and time for last insert/update of the record
      , d.userid -- userid varchar2 8 Y Identification of the user who last inserted/updated the record
      , d.record_version -- record_version number 22 Y Updated whenever a record is inserted/updated to ensure locking
      , d.superordinate_no -- superordinate_no number 22 Y
      , d.legal_form -- legal_form varchar2 2000 Y
      , d.start_date -- start_date date 7 Y
      , d.end_date -- end_date date 7 Y
      , d.location_id_no -- location_id_no number 22 Y
      , d.sellerpid -- sellerpid number 22 Y
      , d.ag_channel -- ag_channel number 22 Y Kanál obchodníka - viz XLA_REFERENCE(AGENT_CHANNEL).
      , d.companyid$$ -- companyid$$ number 22 Y
      , d.agency -- agency varchar2 3 N
      , d.com_group -- com_group varchar2 2 N
      , d.level_code -- level_code number 22 Y
      , d.distribution -- distribution varchar2 2 Y
   /* */ );
```

Do you agree?

**Comment by PhilippSalvisberg** [comment]
Let's look at a simpler example from the [SQL Language Reference](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/MERGE.html#GUID-5692CCB7-24D9-4C0E-81A7-A22436DC968F)

## Original code

```sql
MERGE INTO people_target pt 
USING people_source ps 
ON    (pt.person_id = ps.person_id) 
WHEN matched THEN UPDATE 
  SET pt.first_name = ps.first_name, 
      pt.last_name = ps.last_name, 
      pt.title = ps.title 
  DELETE where pt.title  = 'Mrs.' 
WHEN NOT matched THEN INSERT 
  (pt.person_id, pt.first_name, pt.last_name, pt.title) 
  VALUES (ps.person_id, ps.first_name, ps.last_name, ps.title) 
  WHERE ps.title = 'Mr';
```

## Formatting result with default settings

```sql
MERGE INTO people_target pt
USING people_source ps ON ( pt.person_id = ps.person_id )
WHEN MATCHED THEN UPDATE
SET pt.first_name = ps.first_name,
    pt.last_name = ps.last_name,
    pt.title = ps.title DELETE
 WHERE pt.title = 'Mrs.'
WHEN NOT MATCHED THEN
INSERT (
   pt.person_id,
   pt.first_name,
   pt.last_name,
   pt.title )
VALUES
   ( ps.person_id,
     ps.first_name,
     ps.last_name,
     ps.title )
 WHERE ps.title = 'Mr';
```

## Expected result with default settings

Something like that would be consistent (even if I do not like the line break handling around braces in the insert section)

```sql 
MERGE INTO people_target pt
USING people_source ps 
   ON ( pt.person_id = ps.person_id )
 WHEN MATCHED THEN 
   UPDATE
      SET pt.first_name = ps.first_name,
          pt.last_name = ps.last_name,
          pt.title = ps.title DELETE
    WHERE pt.title = 'Mrs.'
 WHEN NOT MATCHED THEN
   INSERT (
      pt.person_id,
      pt.first_name,
      pt.last_name,
      pt.title
   ) VALUES ( 
      ps.person_id,
      ps.first_name,
      ps.last_name,
      ps.title
   ) WHERE ps.title = 'Mr';
```

**Comment by wienerri** [comment]
I fully agree. Very thanks.
