### ISSUE TITLE
indentExistsSubqueries is throwing error when i try to add to Arbori program in Custom Format of the Preferences

### ISSUE THREAD

**Issue by rthangam** [Trivadis/plsql-formatter-settings#8]
When i try to add the code for indentExistsSubqueries i get the following error:
<img width="522" alt="Screenshot 2020-04-20 at 8 57 28 PM" src="https://user-images.githubusercontent.com/8381334/79769467-c50c7280-8349-11ea-9a10-61d02cde8bd9.png">

Please note that i use SQL developer  Version 19.1.0.094

**Comment by PhilippSalvisberg** [comment]
Thank you @rthangam. 

As mentioned in the [introduction](https://github.com/Trivadis/plsql-formatter-settings#introduction) chapter, the provided settings require a specific version of SQL Developer.

**19.4.0***

The reason for this is that we use JavaScript callbacks which are not supported in 19.1.0. As a result, this error is expected.

I strongly recommend to use the latest version of SQL Developer and import the settings as described.

I'm closing this issue as we do not plan to support old versions of SQL Developer. However, we do plan to support newer versions as they become available.

**Comment by rthangam** [comment]
Thanks Philipp let me try using latest version

**Comment by rthangam** [comment]
I tried using trivadis_advanced_format.xml that works fine but i am unable to use trivadis_custom_format.arbori because of the above error? Does that mean i can't use the settings or something is wrong with the way i am doing it ?

**Comment by PhilippSalvisberg** [comment]
Are you using version 19.4.0?  - This is a mandatory prerequisite. This error will not occur in this version.

**Comment by rthangam** [comment]
Sorry_ for the trouble i will try in 19.4.0 and confirm

**Comment by PhilippSalvisberg** [comment]
No problem. Please let me know, if it works. Thanks.

**Comment by rthangam** [comment]
@PhilippSalvisberg works great!! thanks for the excellent writeup :)
