### ISSUE TITLE
parentheses in where

### ISSUE THREAD

**Issue by wienerri** [Trivadis/plsql-formatter-settings#81]
I use "comma before" setting.
I use parenthesis in where for AND and OR.
I have got after formatting this: 

```sql
SELECT *
  FROM dba_tables
 WHERE ( owner = 'SYSTEM'
   AND ( table_name = 'REDO_DB'
    OR table_name = 'REDO_LOG' ) )
    OR ( owner = 'SYS'
   AND ( table_name = 'ALERT_QT'
    OR table_name = 'ALL_UNIFIED_AUDIT_ACTIONS' ) );
```
There are all conditions optically on the same level, it could be confusing.
I think it would be useful if formatting looks like 

```sql
SELECT *
  FROM dba_tables
 WHERE ( owner = 'SYSTEM'
      AND ( table_name = 'REDO_DB'
            OR table_name = 'REDO_LOG' ) )
    OR ( owner = 'SYS'
      AND ( table_name = 'ALERT_QT'
            OR table_name = 'ALL_UNIFIED_AUDIT_ACTIONS' ) );
```

**Comment by PhilippSalvisberg** [comment]
I agree that the formatting of conditions with parenthesis is not optimal. The change is for sure not simple.

**Comment by wienerri** [comment]
I think you are master of this code - If you think that required workload is not appropriate to required benefit, it is correct  situation and we can close this issue.

**Comment by PhilippSalvisberg** [comment]
It's a valid issue. Therefore I like to keep it open for the time being.

I need a bit more time to think about it. In the end the formatting rules should be consistent. Currently the original SQLDev right-aligning strategy for `AND` and `OR` is consistent. It looks strange with parenthesis or even when mixing `AND` and `OR` conditions without parenthesis. But it is okay for a series of `AND`-only or `OR`-only conditions.

**Comment by PhilippSalvisberg** [comment]
Here's another way to format it which has some consistent logic (treating `AND` and `OR` with parenthesis like functions) but looks strange.

```sql
SELECT *
  FROM dba_tables
 WHERE ( 
          owner = 'SYSTEM'
          AND ( 
             table_name = 'REDO_DB'
             OR table_name = 'REDO_LOG'
          )
       ) OR (
          owner = 'SYS'
         AND (
            table_name = 'ALERT_QT'
            OR table_name = 'ALL_UNIFIED_AUDIT_ACTIONS'
         )
       );
```

When formatting the code by hand the result would be much more compact. Something like this:

```sql
SELECT *
  FROM dba_tables
 WHERE (owner = 'SYSTEM' AND (table_name = 'REDO_DB' OR table_name = 'REDO_LOG'))
    OR (owner = 'SYS' AND (table_name = 'ALERT_QT' OR table_name = 'ALL_UNIFIED_AUDIT_ACTIONS'));
```

So, this is also related to line size and line breaks as we discussed it in issue #33. In this case it's not arguments it's the number of sub-conditions. As soon as we are going to add line breaks to conditions the things become a bit complicated.

**Comment by wienerri** [comment]
It looks pretty good

**Comment by PhilippSalvisberg** [comment]
Formatting this input:

```sql
select * from dba_tables where (owner = 'SYSTEM' and (table_name = 'REDO_DB' or table_name = 'REDO_LOG')) or (owner = 'SYS' and (table_name = 'ALERT_QT' or table_name = 'ALL_UNIFIED_AUDIT_ACTIONS'));
```

with the intermediate version of lightweight formatter (see #105) produces this result:

```sql
select *
  from dba_tables
 where (owner = 'SYSTEM' and (table_name = 'REDO_DB' or table_name = 'REDO_LOG'))
    or (owner = 'SYS' and (table_name = 'ALERT_QT' or table_name = 'ALL_UNIFIED_AUDIT_ACTIONS'));
```
