### ISSUE TITLE
indentation and newlines in function calls 

### ISSUE THREAD

**Issue by jgebal** [Trivadis/plsql-formatter-settings#83]
I get following block post formatting it:
```
declare
  l_value varchar2(4000);
begin
  select /*+ parallel(pd, 4) */ some_quite_long_function_name(another_long_function_name(first_Column_id
                                                                  || another_Column_id
                                                                  || third_Column_id
                                                                  || fourth_column_id
                                                                  || fifth_column
                                                                  || another_column))
    into l_checksum
    from my_table_data pd;
end;
/
```
But I would expect to get something more like below.
The problems that I see are:
- No newline is added after the hint.
- If function names are call parameters are right aligned with function name and therefore their position in code is depending on function name length.

See [this video](https://youtu.be/ZsHMHukIlJY?t=1096) from Kevlin. It explains good code style nicely.

I think it would be much more consistent, maintainable and easy to read like below:
```
declare
  l_value varchar2(4000);
begin
  select /*+ parallel(pd, 4) */ 
         some_quite_long_function_name(
           another_long_function_name(
             first_Column_id
             || another_Column_id
             || third_Column_id
             || fourth_column_id
             || fifth_column
             || another_column
           )
         )
    into l_checksum
    from my_table_data pd;
end;
/
```
This was mentioned by Kevlin Henney in one of his talks.

**Comment by PhilippSalvisberg** [comment]
I see the point. However, defining the rules for this behaviour is not that simple since you do not want to split all functions this way. e.g.

```sql 
select some_quite_long_function_name(
          a,
          b,
          c
       )
  from ...
```

In this case you would like to keep it this way:

```sql 
select some_quite_long_function_name(a, b, c)
  from ...
```

I think this enhancement request is also related to the total line size like other issues #33 and #84.

Regarding the formatting of hints. This is doable based on a lexer logic only. The parse-tree given to the Arbori program does not contain comments nor hints. This means we have to find hints as I've described that in [this blog post](https://www.salvis.com/blog/2020/09/07/highlight-hints-in-sql-developer/) and then add a line break before the next token. 

I agree this needs to be improved, but only in combination with a max-line-size-exceeded-logic.

**Comment by PhilippSalvisberg** [comment]
@jgebal: After closing #33 the result looks now like this:

```sql
declare
   l_value varchar2(4000);
begin
   select /*+ parallel(pd, 4) */ some_quite_long_function_name(
             another_long_function_name(
                first_Column_id
                || another_Column_id
                || third_Column_id
                || fourth_column_id
                || fifth_column
                || another_column
             )
          )
     into l_checksum
     from my_table_data pd;
end;
/
``` 

So, adding a line break after a hint would solve the issue, right?

**Comment by PhilippSalvisberg** [comment]
When you format this code

```sql
select /*+ parallel(t, 2) */
a from t;
```

the result is

```sql
select /*+ parallel(t, 2) */
       a
  from t;
```

But when you format this code:

```sql
select /*+ parallel(t, 2) */  a from t;
```

The result is

```sql
select /*+ parallel(t, 2) */  a
  from t;
```

The serializer component of the SQL Developer formatter preserves the whitespaces after the comment/hint up to a new line.  But new lines are lost.

That's the best I can do.
