### ISSUE TITLE
Decode handling

### ISSUE THREAD

**Issue by anandagollapudi** [Trivadis/plsql-formatter-settings#9]
Thanks Philip for providing direction.
i am currently using your xml and arbori files.
i am using sqlcl 19.1 there i am seeing indentation of  procedure args  increased,
so tried to  below snippet of code you provided. but i am running into parsing error at **" -> { ".**
tried fews changes but couldnt get around parsing error.  arbori format is new to me.
thanks in advance.

` removeWhitspaceInDecodeFunction:  [node) "(x,y,z)" & [node-1) identifier & (?node-1 = 'DECODE') & [node^) function   -> {    var parentNode = tuple.get("node");    var descendants = parentNode.descendants();    for (i = 1, len = descendants.length; i < len; i++) {      var node = descendants.get(i);      var pos = node.from;      var nodeIndent = struct.getNewline(pos);      if (nodeIndent != null) {        struct.putNewline(pos, null);      }    }  };
`

**Comment by PhilippSalvisberg** [comment]
Any reason for using the old version 19.1? That's too old. Please use the newest version 19.4. It cannot work in 19.1 since JavaScript callback are not supported in that version.

**Comment by anandagollapudi** [comment]
Thanks. currently we are using sqlcl 19.1. i was trying to see if i can fix this without version change.
 but if it is version support issue i will upgrade to sqlcl 19.4  and give it a try again.

**Comment by PhilippSalvisberg** [comment]
Yes, you need to update.
