### ISSUE TITLE
SDO_GEOMETRY DDL causes formatting error

### ISSUE THREAD

**Issue by dmcghan** [Trivadis/plsql-formatter-settings#94]
If I create the following table:

```sql
CREATE TABLE t (
  geometry SDO_GEOMETRY
)
```

And then extract the metadata with SEGMENT_ATTRIBUTES set to false:
```sql
BEGIN
  dbms_metadata.set_transform_param(dbms_metadata.session_transform, 'SEGMENT_ATTRIBUTES', false);
  dbms_output.put_line(dbms_metadata.get_ddl('TABLE', 'T', sys_context('userenv', 'current_user')));
END;
```

The resulting DDL looks like this:
```sql
CREATE TABLE "T" 
   (	"GEOMETRY" "SDO_GEOMETRY"
   ) 
 VARRAY "GEOMETRY"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
 VARRAY "GEOMETRY"."SDO_ORDINATES" STORE AS SECUREFILE LOB ;
```

The database recognizes this as valid, but the formatter errors out with:
```
 VARRAY GEOMETRY.SDO_ELEM_INFO STORE AS SECUREFILE LOB 
        ^^^                                             
 
Expected: identifier,... skipped.
```

**Comment by dmcghan** [comment]
Sorry, I should have mentioned that I'm using 

- SQLcl: Release 20.4.1.0 Production Build: 20.4.1.351.1718
- sql_developer/trivadis_advanced_format.xml
- sql_developer/trivadis_custom_format.arbori

**Comment by PhilippSalvisberg** [comment]
I can reproduce the error. It's a bug in the SQL Developer parser. It indicates an error even if the statement can be executed.

![image](https://user-images.githubusercontent.com/3883171/108393950-756e3000-7214-11eb-816c-9446aa2b73df.png)

So, you should ask @thatjeffsmith to fix it.

**Comment by dmcghan** [comment]
Oh, interesting. So the arbori rides on top of SQLDev's built-in parser? I'm still not clear on how all that works...

**Comment by PhilippSalvisberg** [comment]
Yes, The formatter parses the code and Arbori is used to query the parse tree for nodes. The result is "strange" if parse fails, since in SQLDev uses a best effort approach (different to SQLcl).

**Comment by dmcghan** [comment]
Ah, I see. Thanks for the details! :)

**Comment by thatjeffsmith** [comment]
Dan, just a file a bug on SQLDeveloper with the code example.
