### ISSUE TITLE
Whitespace diffs require second formatting run to stabilize

### ISSUE THREAD

**Issue by dmcghan** [Trivadis/plsql-formatter-settings#95]
I'm using:

- SQLcl: Release 20.4.1.0 Production Build: 20.4.1.351.1718
- sql_developer/trivadis_advanced_format.xml
- sql_developer/trivadis_custom_format.arbori

Sometimes packages require a second run of the formatter before subsequent runs don't make any changes. I believe this is only for whitespace diffs, but it would be nice if they could be eliminated.

I've noticed this in a few packages, but there's one I can point two that's publically available:
https://github.com/OraOpenSource/oos-utils/blob/master/source/packages/oos_util_crypto.pkb

Granted, that's a fairly complex package, but I do see this in some of our internal ones that are not as complex.

**Comment by PhilippSalvisberg** [comment]
This is a bug. It's not related to the complexity of the package. I extracted the following code from the `function randombytes`:

```sql
begin
   for i in 0 .. 255
   loop
        t_arcfour.j := mod( t_arcfour.j + t_arcfour.s(i) + t_s2(i), 256 );
        t_tmp := t_arcfour.s(i);
        t_arcfour.s(i) := t_arcfour.s( t_arcfour.j );
        t_arcfour.s( t_arcfour.j ) := t_tmp;
   end loop;
end;
/ 
```

The first formatting result is (intermediate, incomplete):

```sql
begin
   for i in 0..255 loop
      t_arcfour.j                      := mod(t_arcfour.j + t_arcfour.s(i) + t_s2(i), 256);
      t_tmp                            := t_arcfour.s(i);
      t_arcfour.s(i)                   := t_arcfour.s(t_arcfour.j);
      t_arcfour.s(t_arcfour.j)       := t_tmp;
   end loop;
end;
/
```

And the second formatting result is (OK, stabilized):

```sql
begin
   for i in 0..255 loop
      t_arcfour.j                      := mod(t_arcfour.j + t_arcfour.s(i) + t_s2(i), 256);
      t_tmp                            := t_arcfour.s(i);
      t_arcfour.s(i)                   := t_arcfour.s(t_arcfour.j);
      t_arcfour.s(t_arcfour.j)         := t_tmp;
   end loop;
end;
/
```

I believe it is a bug in SQLDev's callback function `pairwiseAlignments` (see [this blog post](https://www.salvis.com/blog/2020/11/12/formatter-callback-functions/#pairwiseAlignments) for more information about this callback function). `pairwiseAlignments` calculations the whitespaces to be inserted between nodes in a top-down approach. This does not work in all constellations. However, we decided to use this callback function in the Arbori program. Therefore I consider it also a bug of our project. It should be solvable with an alternative implementation of `pairwiseAlignments` in JavaScript.

As you figured out yourself, the workaround is to format the code twice to get a stable result.

**Comment by PhilippSalvisberg** [comment]
The result of `pairwiseAlignements` is stable when the left-hand node does not contain unwanted whitespaces.

For example the following would work in one go (no whitespaces in parenthesis of line 7):

```sql
begin
   for i in 0 .. 255
   loop
        t_arcfour.j := mod( t_arcfour.j + t_arcfour.s(i) + t_s2(i), 256 );
        t_tmp := t_arcfour.s(i);
        t_arcfour.s(i) := t_arcfour.s( t_arcfour.j );
        t_arcfour.s(t_arcfour.j) := t_tmp;
   end loop;
end;
/ 
```

**Comment by dmcghan** [comment]
Nice find! Sounds like a timing thing, no? Should `pairwiseAlignements` be called after unwanted whitespace is removed? 

I filed a bug for the one that Jeff said I should. Do you think this is a bug in SQLDev or no?

**Comment by PhilippSalvisberg** [comment]
>Sounds like a timing thing, no? Should pairwiseAlignements be called after unwanted whitespace is removed?

You cannot solve this problem by moving the call of `pairwiseAlignments` to the end of the Arbori program, because the real serialization happens afterwards. And my comment regarding "unwanted whitespaces" was misleading. More precise is probably "whitespace mismatch" which considers missing "wanted whitespaces" as well as in the following example:

```sql
begin
   x(1+2+3) := 'a';
   x(3 + 4 + 5) := 'b';
   x( 3  +  4  +   5) := 'c';
end;
/
```

On line two there where missing whitespaces in the left node.
On line three the whitespaces on the left side match the final ones.
And on line four there are too many whitespaces.

As a result first formatting result looks like this:

```sql
begin
   x(1 + 2 + 3)         := 'a';
   x(3 + 4 + 5)     := 'b';
   x(3 + 4 + 5) := 'c';
end;
/
```

The second formatter call fixes that issue:

```sql
begin
   x(1 + 2 + 3)     := 'a';
   x(3 + 4 + 5)     := 'b';
   x(3 + 4 + 5)     := 'c';
end;
/
```

So the code in `pairwiseAlignment` must properly consider the complete logic applied in the serializer step that runs after the Arbori program when calculating the length of the predecessor nodes. Currently a simplified logic is applied which works in most cases but not in all cases for the first invocation of the formatter.

>Do you think this is a bug in SQLDev or no?

Yes, it is a SQLDev bug. `pairwiseAlignments` is not behaving as it should. The example in this comment should make that clear.

However, in this case we could solve the problem ourselves in the Arbori program, since we can "override" `pairwiseAlignments` via JavaScript.

**Comment by PhilippSalvisberg** [comment]
@dmcghan my previous comment was not accurate. It's a bug in the callback function `paddedIdsInScope` (the callback function `pairwiseAlignments` looks good). 

Sorry for the confusion.

**Comment by dmcghan** [comment]
Got it. I'll file another bug. Thanks!

**Comment by dmcghan** [comment]
Or maybe not. I just tried to reproduce in SQLDev, but it worked as expected there - just one pass needed. I'll hold off on filing another bug in SQLDev for now. Let me know what you think...

**Comment by PhilippSalvisberg** [comment]
I used the default formatting settings in SQLDev 20.4. The only thing I changed was the setting for alignments of the "Assignment Operator :=" (well, we want to align things right? and that's part of the standard SQLDev formatting features).

![image](https://user-images.githubusercontent.com/3883171/108531021-83848500-72d6-11eb-81b6-3d0adc5431ab.png)

Then I formatted the following code:

```sql
begin
   x(1+2+3) := 'a';
   x(3 + 4 + 5) := 'b';
   x( 3  +  4  +   5) := 'c';
   x( 3  +  4  +   5   +  6 ) := 'd';
end;
/
```

The result was:

```sql
BEGIN
    x(1 + 2 + 3)             := 'a';
    x(3 + 4 + 5)         := 'b';
    x(3 + 4 + 5)   := 'c';
    x(3 + 4 + 5 + 6) := 'd';
END;
/
```

The subsequent formatter call produce this result:

```sql
BEGIN
    x(1 + 2 + 3)         := 'a';
    x(3 + 4 + 5)         := 'b';
    x(3 + 4 + 5)         := 'c';
    x(3 + 4 + 5 + 6)     := 'd';
END;
/
```

So I still consider it a SQLDev bug.

**Comment by dmcghan** [comment]
Got it, that's what I missed. I just filed the bug. Thanks again!

**Comment by PhilippSalvisberg** [comment]
Thank you, Dan. Very much appreciated.

**Comment by PhilippSalvisberg** [comment]
I expect that the SQLDev team will fix this bug. In the meantime we have to call the formatter twice for a stable result. I consider that acceptable and don't plan to re-write `paddedIdsInScope` in JavaScript. Hence I close this issue.
