### ISSUE TITLE
Potential issue with conditional compilation

### ISSUE THREAD

**Issue by dmcghan** [Trivadis/plsql-formatter-settings#96]
I'm using:

- SQLcl: Release 20.4.1.0 Production Build: 20.4.1.351.1718
- sql_developer/trivadis_advanced_format.xml
- sql_developer/trivadis_custom_format.arbori

We have some packages that throw errors when formatting. I'm not sure as to the exact cause, but I suspect one of the causes has to do with conditional compilation. There's one where this happens that is publicly available:
https://github.com/OraOpenSource/Logger/blob/master/source/packages/logger.pkb

When formatting that package body, I get:
```
Formatting file 254 of 604: /Users/dmcghan/Downloads/export/packages/logger.pkb... Syntax Error at line 980, column 16
 
 
        end if;
                ^^^
 
Expected: ... skipped.
```

**Comment by PhilippSalvisberg** [comment]
Similar to #94. SQLDev parser gets an error. As a result the code will not be formatted in SQLcl.

![image](https://user-images.githubusercontent.com/3883171/108402279-98e9a880-721d-11eb-87f5-9515f0c43a71.png)

SQLDev can handle conditional compilation. However, handling all constellations is not that easy. Without applying the logic of the pre-compiler it will be virtually impossible to provide a satisfying result for complex cases. And there are cases where the code in conditional compilation blocks does not contain PL/SQL. So, this might be improved in future versions of SQLDev, but cannot be "solved" IMO.

**Comment by dmcghan** [comment]
Good to know. Thanks!
