### ISSUE TITLE
Parantheses following functions/procedures definitions and calls 

### ISSUE THREAD

**Issue by adrianboangiu** [Trivadis/plsql-formatter-settings#99]
Could it be possible to have the parentheses of functions/procedures definition and calls immediately after the function/procedure name?
Several editors are recognizing something as being a function/procedure using this rule.
Thank you

**Comment by PhilippSalvisberg** [comment]
You mean 

```sql
f
(
...
)
```

Yes that's possible to implement via Arbori. However, we like this way:

```
f (
....
)
```

Hence we will not change this.

**Comment by adrianboangiu** [comment]
No. I mean:
f(
...
)
both in definitions and calls.

**Comment by PhilippSalvisberg** [comment]
Well, it works this way. Here's an example for a definition and a usage:

```sql
create or replace package body plscope_context is

   procedure set_attr (
      in_name   in  varchar2,
      in_value  in  varchar2
   ) is
   begin
      sys.dbms_session.set_context(
         namespace  => co_namespace,
         attribute  => in_name,
         value      => in_value
      );
   end set_attr;

end plscope_context;
```

**Comment by adrianboangiu** [comment]
No, what I want is to get rid of the space between the function name and the parentheses. Some text editors recognize a function using this rule:
![image](https://user-images.githubusercontent.com/28983495/111273069-a71bc080-8633-11eb-8870-daf6965ce402.png)
![image](https://user-images.githubusercontent.com/28983495/111273097-af73fb80-8633-11eb-9f69-327fd984bb05.png)

**Comment by PhilippSalvisberg** [comment]
That's possible. But we have to define the behavior very carefully. For functions, procedures, but probably not for other cases such as `.... IN (....`.  An approach would be to remove the unwanted spaces for chosen situations at the end of the Arbori processing. For that I need a closing list of "situations" to handle. Based on examples (text) would be very much appreciated.

**Comment by adrianboangiu** [comment]
I think that among the other cases we shall exclude there is INSERT INTO tablename (…) VALUES (…).
I am not so convinced that we shall exclude:
CURSOR cursorname( arg type,… ) IS SELECT…
and
FOR rec IN cursorname( var, … ) LOOP 
What do you think?

**Comment by PhilippSalvisberg** [comment]
Actually I need an include list. Something like

- Function Definition in create or replace function
- Procedure Definition in create or replace procedure
- ...

For those case I can remove the space between the identifier and the starting parenthesis. So I need a final include list (no "...", "etc." or "similar"). 

A final include list with a final exclude list will work as well.

**Comment by PhilippSalvisberg** [comment]
I'd like to keep it as simple as possible. For me the question/enhancement request is still fuzzy and I'm not sure I understand what you want exactly.

**Comment by adrianboangiu** [comment]
To make it simple and using your example the cases should be:
1.	Function definition (create or replace function)
2.	Package and package body function declaration (function)
3.	Package body function definition (function)
4.	Procedure definition (create or replace procedure)
5.	Package and package body procedure declaration (procedure)
6.	Package body procedure definition (procedure)
7.	Function call
8.	Procedure call
9.	Variable of type Cursor declaration
10.	Variable of type Cursor usage
In all these cases the paranthese introducing the arguments should be immediately after (and on the same line) with the function/procedure/cursor name.

**Comment by PhilippSalvisberg** [comment]
Gotcha. Mostly. Based on the test cases below the cases for 7, 8 and 10 are already covered. Could you please provide examples where the the formatter produces a space before the `(`? Thank you.

The test cases (input and expected result):

>1. Function definition (create or replace function)

```sql
create or replace function f(
   p1 in integer
) return integer is
begin
   return 1;
end;
/
```

>2. Package and package body function declaration (function)

```sql
create or replace package pkg is
   function f(
      p1 in integer
   ) return integer;
end;
/

create or replace package body pkg is
   function f(
      p1 in integer
   ) return integer;
end;
/
```

>3. Package body function definition (function)

```sql
create or replace package body pkg is
   function f(
      p1 in integer
   ) return integer is
   begin
      return 1;
   end;
end;
/
```

>4. Procedure definition (create or replace procedure)

```sql
create or replace procedure p(
   p1 in integer
) is
begin
   null;
end;
/
```

>5. Package and package body procedure declaration (procedure)

```sql
create or replace package pkg is
   procedure p(
      p1 in integer
   );
end;
/

create or replace package body pkg is
   procedure p(
      p1 in integer
   );
end;
/
```

>6. Package body procedure definition (procedure)

```sql
create or replace package body pkg is
   procedure p(
      p1 in integer
   ) is
   begin
      null;
   end;
end;
/
```

>7. Function call

This is already covered!

```sql
select f(
          1,
          2,
          3,
          4,
          5
       )
  from dual;
```

>8. Procedure call

This is already covered!

```sql
begin
   p(
      1,
      2,
      3,
      4,
      5
   );
end;
/
```

>9. Variable of type Cursor declaration

```sql
declare
   cursor c1(
      p1 in varchar2
   ) is
      select col1
        from t
       where col2 = p1;
begin
   null;
end;
/
```

>10. Variable of type Cursor usage

This is already covered!

```sql
begin
   open c2(
      1,
      2,
      3,
      4,
      5
   );
end;
/
```
